from __future__ import annotations
from dataclasses import dataclass
import typing as tp
from typing import overload
from typing_extensions import Self
from ._gl_common import uint, double
_TItem = tp.TypeVar('_TItem', int, float, uint, double, bool)
_UItem = int | float | uint | double | bool
_Never = tp.NoReturn
_NV: tp.Any = None


@dataclass
class _vec_seq(tp.Generic[_TItem]):
    def __getitem__(self, index: int) -> _TItem: ...
    def __setitem__(self, index: int, value: _TItem): ...
    def length(self) -> int: ...


@dataclass
class _vec_op(tp.Generic[_TItem]):
    @overload
    def __add__(self, other: _TItem) -> Self: ...
    @overload
    def __add__(self, other: Self) -> Self: ...
    def __add__(self, other) -> Self: ...
    @overload
    def __sub__(self, other: _TItem) -> Self: ...
    @overload
    def __sub__(self, other: Self) -> Self: ...
    def __sub__(self, other) -> Self: ...
    @overload
    def __mul__(self, other: _TItem) -> Self: ...
    @overload
    def __mul__(self, other: Self) -> Self: ...
    def __mul__(self, other) -> Self: ...
    @overload
    def __truediv__(self, other: _TItem) -> Self: ...
    @overload
    def __truediv__(self, other: Self) -> Self: ...
    def __truediv__(self, other) -> Self: ...
    @overload
    def __radd__(self, other: _TItem) -> Self: ...
    @overload
    def __radd__(self, other: Self) -> Self: ...
    def __radd__(self, other) -> Self: ...
    @overload
    def __rsub__(self, other: _TItem) -> Self: ...
    @overload
    def __rsub__(self, other: Self) -> Self: ...
    def __rsub__(self, other) -> Self: ...
    @overload
    def __rmul__(self, other: _TItem) -> Self: ...
    @overload
    def __rmul__(self, other: Self) -> Self: ...
    def __rmul__(self, other) -> Self: ...
    @overload
    def __rtruediv__(self, other: _TItem) -> Self: ...
    @overload
    def __rtruediv__(self, other: Self) -> Self: ...
    def __rtruediv__(self, other) -> Self: ...


@dataclass
class _2d_prop(tp.Generic[_TItem]):

    @property
    def x(self) -> _TItem: ...
    @x.setter
    def x(self, value: _TItem): ...
    @property
    def y(self) -> _TItem: ...
    @y.setter
    def y(self, value: _TItem): ...
    @property
    def xy(self) -> gvec2[_TItem]: ...
    @xy.setter
    def xy(self, value: gvec2[_TItem]): ...
    @property
    def yx(self) -> gvec2[_TItem]: ...
    @yx.setter
    def yx(self, value: gvec2[_TItem]): ...
    @property
    def xx(self) -> gvec2[_TItem]: ...
    @property
    def yy(self) -> gvec2[_TItem]: ...
    @property
    def xxx(self) -> gvec3[_TItem]: ...
    @property
    def xxy(self) -> gvec3[_TItem]: ...
    @property
    def xyx(self) -> gvec3[_TItem]: ...
    @property
    def xyy(self) -> gvec3[_TItem]: ...
    @property
    def yxx(self) -> gvec3[_TItem]: ...
    @property
    def yxy(self) -> gvec3[_TItem]: ...
    @property
    def yyx(self) -> gvec3[_TItem]: ...
    @property
    def yyy(self) -> gvec3[_TItem]: ...
    @property
    def xxxx(self) -> gvec4[_TItem]: ...
    @property
    def xxxy(self) -> gvec4[_TItem]: ...
    @property
    def xxyx(self) -> gvec4[_TItem]: ...
    @property
    def xxyy(self) -> gvec4[_TItem]: ...
    @property
    def xyxx(self) -> gvec4[_TItem]: ...
    @property
    def xyxy(self) -> gvec4[_TItem]: ...
    @property
    def xyyx(self) -> gvec4[_TItem]: ...
    @property
    def xyyy(self) -> gvec4[_TItem]: ...
    @property
    def yxxx(self) -> gvec4[_TItem]: ...
    @property
    def yxxy(self) -> gvec4[_TItem]: ...
    @property
    def yxyx(self) -> gvec4[_TItem]: ...
    @property
    def yxyy(self) -> gvec4[_TItem]: ...
    @property
    def yyxx(self) -> gvec4[_TItem]: ...
    @property
    def yyxy(self) -> gvec4[_TItem]: ...
    @property
    def yyyx(self) -> gvec4[_TItem]: ...
    @property
    def yyyy(self) -> gvec4[_TItem]: ...
    @property
    def r(self) -> _TItem: ...
    @r.setter
    def r(self, value: _TItem): ...
    @property
    def g(self) -> _TItem: ...
    @g.setter
    def g(self, value: _TItem): ...
    @property
    def rg(self) -> gvec2[_TItem]: ...
    @rg.setter
    def rg(self, value: gvec2[_TItem]): ...
    @property
    def gr(self) -> gvec2[_TItem]: ...
    @gr.setter
    def gr(self, value: gvec2[_TItem]): ...
    @property
    def rr(self) -> gvec2[_TItem]: ...
    @property
    def gg(self) -> gvec2[_TItem]: ...
    @property
    def rrr(self) -> gvec3[_TItem]: ...
    @property
    def rrg(self) -> gvec3[_TItem]: ...
    @property
    def rgr(self) -> gvec3[_TItem]: ...
    @property
    def rgg(self) -> gvec3[_TItem]: ...
    @property
    def grr(self) -> gvec3[_TItem]: ...
    @property
    def grg(self) -> gvec3[_TItem]: ...
    @property
    def ggr(self) -> gvec3[_TItem]: ...
    @property
    def ggg(self) -> gvec3[_TItem]: ...
    @property
    def rrrr(self) -> gvec4[_TItem]: ...
    @property
    def rrrg(self) -> gvec4[_TItem]: ...
    @property
    def rrgr(self) -> gvec4[_TItem]: ...
    @property
    def rrgg(self) -> gvec4[_TItem]: ...
    @property
    def rgrr(self) -> gvec4[_TItem]: ...
    @property
    def rgrg(self) -> gvec4[_TItem]: ...
    @property
    def rggr(self) -> gvec4[_TItem]: ...
    @property
    def rggg(self) -> gvec4[_TItem]: ...
    @property
    def grrr(self) -> gvec4[_TItem]: ...
    @property
    def grrg(self) -> gvec4[_TItem]: ...
    @property
    def grgr(self) -> gvec4[_TItem]: ...
    @property
    def grgg(self) -> gvec4[_TItem]: ...
    @property
    def ggrr(self) -> gvec4[_TItem]: ...
    @property
    def ggrg(self) -> gvec4[_TItem]: ...
    @property
    def gggr(self) -> gvec4[_TItem]: ...
    @property
    def gggg(self) -> gvec4[_TItem]: ...
    @property
    def s(self) -> _TItem: ...
    @s.setter
    def s(self, value: _TItem): ...
    @property
    def t(self) -> _TItem: ...
    @t.setter
    def t(self, value: _TItem): ...
    @property
    def st(self) -> gvec2[_TItem]: ...
    @st.setter
    def st(self, value: gvec2[_TItem]): ...
    @property
    def ts(self) -> gvec2[_TItem]: ...
    @ts.setter
    def ts(self, value: gvec2[_TItem]): ...
    @property
    def ss(self) -> gvec2[_TItem]: ...
    @property
    def tt(self) -> gvec2[_TItem]: ...
    @property
    def sss(self) -> gvec3[_TItem]: ...
    @property
    def sst(self) -> gvec3[_TItem]: ...
    @property
    def sts(self) -> gvec3[_TItem]: ...
    @property
    def stt(self) -> gvec3[_TItem]: ...
    @property
    def tss(self) -> gvec3[_TItem]: ...
    @property
    def tst(self) -> gvec3[_TItem]: ...
    @property
    def tts(self) -> gvec3[_TItem]: ...
    @property
    def ttt(self) -> gvec3[_TItem]: ...
    @property
    def ssss(self) -> gvec4[_TItem]: ...
    @property
    def ssst(self) -> gvec4[_TItem]: ...
    @property
    def ssts(self) -> gvec4[_TItem]: ...
    @property
    def sstt(self) -> gvec4[_TItem]: ...
    @property
    def stss(self) -> gvec4[_TItem]: ...
    @property
    def stst(self) -> gvec4[_TItem]: ...
    @property
    def stts(self) -> gvec4[_TItem]: ...
    @property
    def sttt(self) -> gvec4[_TItem]: ...
    @property
    def tsss(self) -> gvec4[_TItem]: ...
    @property
    def tsst(self) -> gvec4[_TItem]: ...
    @property
    def tsts(self) -> gvec4[_TItem]: ...
    @property
    def tstt(self) -> gvec4[_TItem]: ...
    @property
    def ttss(self) -> gvec4[_TItem]: ...
    @property
    def ttst(self) -> gvec4[_TItem]: ...
    @property
    def ttts(self) -> gvec4[_TItem]: ...
    @property
    def tttt(self) -> gvec4[_TItem]: ...


@dataclass
class _3d_prop(tp.Generic[_TItem]):

    @property
    def x(self) -> _TItem: ...
    @x.setter
    def x(self, value: _TItem): ...
    @property
    def y(self) -> _TItem: ...
    @y.setter
    def y(self, value: _TItem): ...
    @property
    def z(self) -> _TItem: ...
    @z.setter
    def z(self, value: _TItem): ...
    @property
    def xy(self) -> gvec2[_TItem]: ...
    @xy.setter
    def xy(self, value: gvec2[_TItem]): ...
    @property
    def xz(self) -> gvec2[_TItem]: ...
    @xz.setter
    def xz(self, value: gvec2[_TItem]): ...
    @property
    def yx(self) -> gvec2[_TItem]: ...
    @yx.setter
    def yx(self, value: gvec2[_TItem]): ...
    @property
    def yz(self) -> gvec2[_TItem]: ...
    @yz.setter
    def yz(self, value: gvec2[_TItem]): ...
    @property
    def zx(self) -> gvec2[_TItem]: ...
    @zx.setter
    def zx(self, value: gvec2[_TItem]): ...
    @property
    def zy(self) -> gvec2[_TItem]: ...
    @zy.setter
    def zy(self, value: gvec2[_TItem]): ...
    @property
    def xyz(self) -> gvec3[_TItem]: ...
    @xyz.setter
    def xyz(self, value: gvec3[_TItem]): ...
    @property
    def xzy(self) -> gvec3[_TItem]: ...
    @xzy.setter
    def xzy(self, value: gvec3[_TItem]): ...
    @property
    def yxz(self) -> gvec3[_TItem]: ...
    @yxz.setter
    def yxz(self, value: gvec3[_TItem]): ...
    @property
    def yzx(self) -> gvec3[_TItem]: ...
    @yzx.setter
    def yzx(self, value: gvec3[_TItem]): ...
    @property
    def zxy(self) -> gvec3[_TItem]: ...
    @zxy.setter
    def zxy(self, value: gvec3[_TItem]): ...
    @property
    def zyx(self) -> gvec3[_TItem]: ...
    @zyx.setter
    def zyx(self, value: gvec3[_TItem]): ...
    @property
    def xx(self) -> gvec2[_TItem]: ...
    @property
    def yy(self) -> gvec2[_TItem]: ...
    @property
    def zz(self) -> gvec2[_TItem]: ...
    @property
    def xxx(self) -> gvec3[_TItem]: ...
    @property
    def xxy(self) -> gvec3[_TItem]: ...
    @property
    def xxz(self) -> gvec3[_TItem]: ...
    @property
    def xyx(self) -> gvec3[_TItem]: ...
    @property
    def xyy(self) -> gvec3[_TItem]: ...
    @property
    def xzx(self) -> gvec3[_TItem]: ...
    @property
    def xzz(self) -> gvec3[_TItem]: ...
    @property
    def yxx(self) -> gvec3[_TItem]: ...
    @property
    def yxy(self) -> gvec3[_TItem]: ...
    @property
    def yyx(self) -> gvec3[_TItem]: ...
    @property
    def yyy(self) -> gvec3[_TItem]: ...
    @property
    def yyz(self) -> gvec3[_TItem]: ...
    @property
    def yzy(self) -> gvec3[_TItem]: ...
    @property
    def yzz(self) -> gvec3[_TItem]: ...
    @property
    def zxx(self) -> gvec3[_TItem]: ...
    @property
    def zxz(self) -> gvec3[_TItem]: ...
    @property
    def zyy(self) -> gvec3[_TItem]: ...
    @property
    def zyz(self) -> gvec3[_TItem]: ...
    @property
    def zzx(self) -> gvec3[_TItem]: ...
    @property
    def zzy(self) -> gvec3[_TItem]: ...
    @property
    def zzz(self) -> gvec3[_TItem]: ...
    @property
    def xxxx(self) -> gvec4[_TItem]: ...
    @property
    def xxxy(self) -> gvec4[_TItem]: ...
    @property
    def xxxz(self) -> gvec4[_TItem]: ...
    @property
    def xxyx(self) -> gvec4[_TItem]: ...
    @property
    def xxyy(self) -> gvec4[_TItem]: ...
    @property
    def xxyz(self) -> gvec4[_TItem]: ...
    @property
    def xxzx(self) -> gvec4[_TItem]: ...
    @property
    def xxzy(self) -> gvec4[_TItem]: ...
    @property
    def xxzz(self) -> gvec4[_TItem]: ...
    @property
    def xyxx(self) -> gvec4[_TItem]: ...
    @property
    def xyxy(self) -> gvec4[_TItem]: ...
    @property
    def xyxz(self) -> gvec4[_TItem]: ...
    @property
    def xyyx(self) -> gvec4[_TItem]: ...
    @property
    def xyyy(self) -> gvec4[_TItem]: ...
    @property
    def xyyz(self) -> gvec4[_TItem]: ...
    @property
    def xyzx(self) -> gvec4[_TItem]: ...
    @property
    def xyzy(self) -> gvec4[_TItem]: ...
    @property
    def xyzz(self) -> gvec4[_TItem]: ...
    @property
    def xzxx(self) -> gvec4[_TItem]: ...
    @property
    def xzxy(self) -> gvec4[_TItem]: ...
    @property
    def xzxz(self) -> gvec4[_TItem]: ...
    @property
    def xzyx(self) -> gvec4[_TItem]: ...
    @property
    def xzyy(self) -> gvec4[_TItem]: ...
    @property
    def xzyz(self) -> gvec4[_TItem]: ...
    @property
    def xzzx(self) -> gvec4[_TItem]: ...
    @property
    def xzzy(self) -> gvec4[_TItem]: ...
    @property
    def xzzz(self) -> gvec4[_TItem]: ...
    @property
    def yxxx(self) -> gvec4[_TItem]: ...
    @property
    def yxxy(self) -> gvec4[_TItem]: ...
    @property
    def yxxz(self) -> gvec4[_TItem]: ...
    @property
    def yxyx(self) -> gvec4[_TItem]: ...
    @property
    def yxyy(self) -> gvec4[_TItem]: ...
    @property
    def yxyz(self) -> gvec4[_TItem]: ...
    @property
    def yxzx(self) -> gvec4[_TItem]: ...
    @property
    def yxzy(self) -> gvec4[_TItem]: ...
    @property
    def yxzz(self) -> gvec4[_TItem]: ...
    @property
    def yyxx(self) -> gvec4[_TItem]: ...
    @property
    def yyxy(self) -> gvec4[_TItem]: ...
    @property
    def yyxz(self) -> gvec4[_TItem]: ...
    @property
    def yyyx(self) -> gvec4[_TItem]: ...
    @property
    def yyyy(self) -> gvec4[_TItem]: ...
    @property
    def yyyz(self) -> gvec4[_TItem]: ...
    @property
    def yyzx(self) -> gvec4[_TItem]: ...
    @property
    def yyzy(self) -> gvec4[_TItem]: ...
    @property
    def yyzz(self) -> gvec4[_TItem]: ...
    @property
    def yzxx(self) -> gvec4[_TItem]: ...
    @property
    def yzxy(self) -> gvec4[_TItem]: ...
    @property
    def yzxz(self) -> gvec4[_TItem]: ...
    @property
    def yzyx(self) -> gvec4[_TItem]: ...
    @property
    def yzyy(self) -> gvec4[_TItem]: ...
    @property
    def yzyz(self) -> gvec4[_TItem]: ...
    @property
    def yzzx(self) -> gvec4[_TItem]: ...
    @property
    def yzzy(self) -> gvec4[_TItem]: ...
    @property
    def yzzz(self) -> gvec4[_TItem]: ...
    @property
    def zxxx(self) -> gvec4[_TItem]: ...
    @property
    def zxxy(self) -> gvec4[_TItem]: ...
    @property
    def zxxz(self) -> gvec4[_TItem]: ...
    @property
    def zxyx(self) -> gvec4[_TItem]: ...
    @property
    def zxyy(self) -> gvec4[_TItem]: ...
    @property
    def zxyz(self) -> gvec4[_TItem]: ...
    @property
    def zxzx(self) -> gvec4[_TItem]: ...
    @property
    def zxzy(self) -> gvec4[_TItem]: ...
    @property
    def zxzz(self) -> gvec4[_TItem]: ...
    @property
    def zyxx(self) -> gvec4[_TItem]: ...
    @property
    def zyxy(self) -> gvec4[_TItem]: ...
    @property
    def zyxz(self) -> gvec4[_TItem]: ...
    @property
    def zyyx(self) -> gvec4[_TItem]: ...
    @property
    def zyyy(self) -> gvec4[_TItem]: ...
    @property
    def zyyz(self) -> gvec4[_TItem]: ...
    @property
    def zyzx(self) -> gvec4[_TItem]: ...
    @property
    def zyzy(self) -> gvec4[_TItem]: ...
    @property
    def zyzz(self) -> gvec4[_TItem]: ...
    @property
    def zzxx(self) -> gvec4[_TItem]: ...
    @property
    def zzxy(self) -> gvec4[_TItem]: ...
    @property
    def zzxz(self) -> gvec4[_TItem]: ...
    @property
    def zzyx(self) -> gvec4[_TItem]: ...
    @property
    def zzyy(self) -> gvec4[_TItem]: ...
    @property
    def zzyz(self) -> gvec4[_TItem]: ...
    @property
    def zzzx(self) -> gvec4[_TItem]: ...
    @property
    def zzzy(self) -> gvec4[_TItem]: ...
    @property
    def zzzz(self) -> gvec4[_TItem]: ...
    @property
    def r(self) -> _TItem: ...
    @r.setter
    def r(self, value: _TItem): ...
    @property
    def g(self) -> _TItem: ...
    @g.setter
    def g(self, value: _TItem): ...
    @property
    def b(self) -> _TItem: ...
    @b.setter
    def b(self, value: _TItem): ...
    @property
    def rg(self) -> gvec2[_TItem]: ...
    @rg.setter
    def rg(self, value: gvec2[_TItem]): ...
    @property
    def rb(self) -> gvec2[_TItem]: ...
    @rb.setter
    def rb(self, value: gvec2[_TItem]): ...
    @property
    def gr(self) -> gvec2[_TItem]: ...
    @gr.setter
    def gr(self, value: gvec2[_TItem]): ...
    @property
    def gb(self) -> gvec2[_TItem]: ...
    @gb.setter
    def gb(self, value: gvec2[_TItem]): ...
    @property
    def br(self) -> gvec2[_TItem]: ...
    @br.setter
    def br(self, value: gvec2[_TItem]): ...
    @property
    def bg(self) -> gvec2[_TItem]: ...
    @bg.setter
    def bg(self, value: gvec2[_TItem]): ...
    @property
    def rgb(self) -> gvec3[_TItem]: ...
    @rgb.setter
    def rgb(self, value: gvec3[_TItem]): ...
    @property
    def rbg(self) -> gvec3[_TItem]: ...
    @rbg.setter
    def rbg(self, value: gvec3[_TItem]): ...
    @property
    def grb(self) -> gvec3[_TItem]: ...
    @grb.setter
    def grb(self, value: gvec3[_TItem]): ...
    @property
    def gbr(self) -> gvec3[_TItem]: ...
    @gbr.setter
    def gbr(self, value: gvec3[_TItem]): ...
    @property
    def brg(self) -> gvec3[_TItem]: ...
    @brg.setter
    def brg(self, value: gvec3[_TItem]): ...
    @property
    def bgr(self) -> gvec3[_TItem]: ...
    @bgr.setter
    def bgr(self, value: gvec3[_TItem]): ...
    @property
    def rr(self) -> gvec2[_TItem]: ...
    @property
    def gg(self) -> gvec2[_TItem]: ...
    @property
    def bb(self) -> gvec2[_TItem]: ...
    @property
    def rrr(self) -> gvec3[_TItem]: ...
    @property
    def rrg(self) -> gvec3[_TItem]: ...
    @property
    def rrb(self) -> gvec3[_TItem]: ...
    @property
    def rgr(self) -> gvec3[_TItem]: ...
    @property
    def rgg(self) -> gvec3[_TItem]: ...
    @property
    def rbr(self) -> gvec3[_TItem]: ...
    @property
    def rbb(self) -> gvec3[_TItem]: ...
    @property
    def grr(self) -> gvec3[_TItem]: ...
    @property
    def grg(self) -> gvec3[_TItem]: ...
    @property
    def ggr(self) -> gvec3[_TItem]: ...
    @property
    def ggg(self) -> gvec3[_TItem]: ...
    @property
    def ggb(self) -> gvec3[_TItem]: ...
    @property
    def gbg(self) -> gvec3[_TItem]: ...
    @property
    def gbb(self) -> gvec3[_TItem]: ...
    @property
    def brr(self) -> gvec3[_TItem]: ...
    @property
    def brb(self) -> gvec3[_TItem]: ...
    @property
    def bgg(self) -> gvec3[_TItem]: ...
    @property
    def bgb(self) -> gvec3[_TItem]: ...
    @property
    def bbr(self) -> gvec3[_TItem]: ...
    @property
    def bbg(self) -> gvec3[_TItem]: ...
    @property
    def bbb(self) -> gvec3[_TItem]: ...
    @property
    def rrrr(self) -> gvec4[_TItem]: ...
    @property
    def rrrg(self) -> gvec4[_TItem]: ...
    @property
    def rrrb(self) -> gvec4[_TItem]: ...
    @property
    def rrgr(self) -> gvec4[_TItem]: ...
    @property
    def rrgg(self) -> gvec4[_TItem]: ...
    @property
    def rrgb(self) -> gvec4[_TItem]: ...
    @property
    def rrbr(self) -> gvec4[_TItem]: ...
    @property
    def rrbg(self) -> gvec4[_TItem]: ...
    @property
    def rrbb(self) -> gvec4[_TItem]: ...
    @property
    def rgrr(self) -> gvec4[_TItem]: ...
    @property
    def rgrg(self) -> gvec4[_TItem]: ...
    @property
    def rgrb(self) -> gvec4[_TItem]: ...
    @property
    def rggr(self) -> gvec4[_TItem]: ...
    @property
    def rggg(self) -> gvec4[_TItem]: ...
    @property
    def rggb(self) -> gvec4[_TItem]: ...
    @property
    def rgbr(self) -> gvec4[_TItem]: ...
    @property
    def rgbg(self) -> gvec4[_TItem]: ...
    @property
    def rgbb(self) -> gvec4[_TItem]: ...
    @property
    def rbrr(self) -> gvec4[_TItem]: ...
    @property
    def rbrg(self) -> gvec4[_TItem]: ...
    @property
    def rbrb(self) -> gvec4[_TItem]: ...
    @property
    def rbgr(self) -> gvec4[_TItem]: ...
    @property
    def rbgg(self) -> gvec4[_TItem]: ...
    @property
    def rbgb(self) -> gvec4[_TItem]: ...
    @property
    def rbbr(self) -> gvec4[_TItem]: ...
    @property
    def rbbg(self) -> gvec4[_TItem]: ...
    @property
    def rbbb(self) -> gvec4[_TItem]: ...
    @property
    def grrr(self) -> gvec4[_TItem]: ...
    @property
    def grrg(self) -> gvec4[_TItem]: ...
    @property
    def grrb(self) -> gvec4[_TItem]: ...
    @property
    def grgr(self) -> gvec4[_TItem]: ...
    @property
    def grgg(self) -> gvec4[_TItem]: ...
    @property
    def grgb(self) -> gvec4[_TItem]: ...
    @property
    def grbr(self) -> gvec4[_TItem]: ...
    @property
    def grbg(self) -> gvec4[_TItem]: ...
    @property
    def grbb(self) -> gvec4[_TItem]: ...
    @property
    def ggrr(self) -> gvec4[_TItem]: ...
    @property
    def ggrg(self) -> gvec4[_TItem]: ...
    @property
    def ggrb(self) -> gvec4[_TItem]: ...
    @property
    def gggr(self) -> gvec4[_TItem]: ...
    @property
    def gggg(self) -> gvec4[_TItem]: ...
    @property
    def gggb(self) -> gvec4[_TItem]: ...
    @property
    def ggbr(self) -> gvec4[_TItem]: ...
    @property
    def ggbg(self) -> gvec4[_TItem]: ...
    @property
    def ggbb(self) -> gvec4[_TItem]: ...
    @property
    def gbrr(self) -> gvec4[_TItem]: ...
    @property
    def gbrg(self) -> gvec4[_TItem]: ...
    @property
    def gbrb(self) -> gvec4[_TItem]: ...
    @property
    def gbgr(self) -> gvec4[_TItem]: ...
    @property
    def gbgg(self) -> gvec4[_TItem]: ...
    @property
    def gbgb(self) -> gvec4[_TItem]: ...
    @property
    def gbbr(self) -> gvec4[_TItem]: ...
    @property
    def gbbg(self) -> gvec4[_TItem]: ...
    @property
    def gbbb(self) -> gvec4[_TItem]: ...
    @property
    def brrr(self) -> gvec4[_TItem]: ...
    @property
    def brrg(self) -> gvec4[_TItem]: ...
    @property
    def brrb(self) -> gvec4[_TItem]: ...
    @property
    def brgr(self) -> gvec4[_TItem]: ...
    @property
    def brgg(self) -> gvec4[_TItem]: ...
    @property
    def brgb(self) -> gvec4[_TItem]: ...
    @property
    def brbr(self) -> gvec4[_TItem]: ...
    @property
    def brbg(self) -> gvec4[_TItem]: ...
    @property
    def brbb(self) -> gvec4[_TItem]: ...
    @property
    def bgrr(self) -> gvec4[_TItem]: ...
    @property
    def bgrg(self) -> gvec4[_TItem]: ...
    @property
    def bgrb(self) -> gvec4[_TItem]: ...
    @property
    def bggr(self) -> gvec4[_TItem]: ...
    @property
    def bggg(self) -> gvec4[_TItem]: ...
    @property
    def bggb(self) -> gvec4[_TItem]: ...
    @property
    def bgbr(self) -> gvec4[_TItem]: ...
    @property
    def bgbg(self) -> gvec4[_TItem]: ...
    @property
    def bgbb(self) -> gvec4[_TItem]: ...
    @property
    def bbrr(self) -> gvec4[_TItem]: ...
    @property
    def bbrg(self) -> gvec4[_TItem]: ...
    @property
    def bbrb(self) -> gvec4[_TItem]: ...
    @property
    def bbgr(self) -> gvec4[_TItem]: ...
    @property
    def bbgg(self) -> gvec4[_TItem]: ...
    @property
    def bbgb(self) -> gvec4[_TItem]: ...
    @property
    def bbbr(self) -> gvec4[_TItem]: ...
    @property
    def bbbg(self) -> gvec4[_TItem]: ...
    @property
    def bbbb(self) -> gvec4[_TItem]: ...
    @property
    def s(self) -> _TItem: ...
    @s.setter
    def s(self, value: _TItem): ...
    @property
    def t(self) -> _TItem: ...
    @t.setter
    def t(self, value: _TItem): ...
    @property
    def p(self) -> _TItem: ...
    @p.setter
    def p(self, value: _TItem): ...
    @property
    def st(self) -> gvec2[_TItem]: ...
    @st.setter
    def st(self, value: gvec2[_TItem]): ...
    @property
    def sp(self) -> gvec2[_TItem]: ...
    @sp.setter
    def sp(self, value: gvec2[_TItem]): ...
    @property
    def ts(self) -> gvec2[_TItem]: ...
    @ts.setter
    def ts(self, value: gvec2[_TItem]): ...
    @property
    def tp(self) -> gvec2[_TItem]: ...
    @tp.setter
    def tp(self, value: gvec2[_TItem]): ...
    @property
    def ps(self) -> gvec2[_TItem]: ...
    @ps.setter
    def ps(self, value: gvec2[_TItem]): ...
    @property
    def pt(self) -> gvec2[_TItem]: ...
    @pt.setter
    def pt(self, value: gvec2[_TItem]): ...
    @property
    def stp(self) -> gvec3[_TItem]: ...
    @stp.setter
    def stp(self, value: gvec3[_TItem]): ...
    @property
    def spt(self) -> gvec3[_TItem]: ...
    @spt.setter
    def spt(self, value: gvec3[_TItem]): ...
    @property
    def tsp(self) -> gvec3[_TItem]: ...
    @tsp.setter
    def tsp(self, value: gvec3[_TItem]): ...
    @property
    def tps(self) -> gvec3[_TItem]: ...
    @tps.setter
    def tps(self, value: gvec3[_TItem]): ...
    @property
    def pst(self) -> gvec3[_TItem]: ...
    @pst.setter
    def pst(self, value: gvec3[_TItem]): ...
    @property
    def pts(self) -> gvec3[_TItem]: ...
    @pts.setter
    def pts(self, value: gvec3[_TItem]): ...
    @property
    def ss(self) -> gvec2[_TItem]: ...
    @property
    def tt(self) -> gvec2[_TItem]: ...
    @property
    def pp(self) -> gvec2[_TItem]: ...
    @property
    def sss(self) -> gvec3[_TItem]: ...
    @property
    def sst(self) -> gvec3[_TItem]: ...
    @property
    def ssp(self) -> gvec3[_TItem]: ...
    @property
    def sts(self) -> gvec3[_TItem]: ...
    @property
    def stt(self) -> gvec3[_TItem]: ...
    @property
    def sps(self) -> gvec3[_TItem]: ...
    @property
    def spp(self) -> gvec3[_TItem]: ...
    @property
    def tss(self) -> gvec3[_TItem]: ...
    @property
    def tst(self) -> gvec3[_TItem]: ...
    @property
    def tts(self) -> gvec3[_TItem]: ...
    @property
    def ttt(self) -> gvec3[_TItem]: ...
    @property
    def ttp(self) -> gvec3[_TItem]: ...
    @property
    def tpt(self) -> gvec3[_TItem]: ...
    @property
    def tpp(self) -> gvec3[_TItem]: ...
    @property
    def pss(self) -> gvec3[_TItem]: ...
    @property
    def psp(self) -> gvec3[_TItem]: ...
    @property
    def ptt(self) -> gvec3[_TItem]: ...
    @property
    def ptp(self) -> gvec3[_TItem]: ...
    @property
    def pps(self) -> gvec3[_TItem]: ...
    @property
    def ppt(self) -> gvec3[_TItem]: ...
    @property
    def ppp(self) -> gvec3[_TItem]: ...
    @property
    def ssss(self) -> gvec4[_TItem]: ...
    @property
    def ssst(self) -> gvec4[_TItem]: ...
    @property
    def sssp(self) -> gvec4[_TItem]: ...
    @property
    def ssts(self) -> gvec4[_TItem]: ...
    @property
    def sstt(self) -> gvec4[_TItem]: ...
    @property
    def sstp(self) -> gvec4[_TItem]: ...
    @property
    def ssps(self) -> gvec4[_TItem]: ...
    @property
    def sspt(self) -> gvec4[_TItem]: ...
    @property
    def sspp(self) -> gvec4[_TItem]: ...
    @property
    def stss(self) -> gvec4[_TItem]: ...
    @property
    def stst(self) -> gvec4[_TItem]: ...
    @property
    def stsp(self) -> gvec4[_TItem]: ...
    @property
    def stts(self) -> gvec4[_TItem]: ...
    @property
    def sttt(self) -> gvec4[_TItem]: ...
    @property
    def sttp(self) -> gvec4[_TItem]: ...
    @property
    def stps(self) -> gvec4[_TItem]: ...
    @property
    def stpt(self) -> gvec4[_TItem]: ...
    @property
    def stpp(self) -> gvec4[_TItem]: ...
    @property
    def spss(self) -> gvec4[_TItem]: ...
    @property
    def spst(self) -> gvec4[_TItem]: ...
    @property
    def spsp(self) -> gvec4[_TItem]: ...
    @property
    def spts(self) -> gvec4[_TItem]: ...
    @property
    def sptt(self) -> gvec4[_TItem]: ...
    @property
    def sptp(self) -> gvec4[_TItem]: ...
    @property
    def spps(self) -> gvec4[_TItem]: ...
    @property
    def sppt(self) -> gvec4[_TItem]: ...
    @property
    def sppp(self) -> gvec4[_TItem]: ...
    @property
    def tsss(self) -> gvec4[_TItem]: ...
    @property
    def tsst(self) -> gvec4[_TItem]: ...
    @property
    def tssp(self) -> gvec4[_TItem]: ...
    @property
    def tsts(self) -> gvec4[_TItem]: ...
    @property
    def tstt(self) -> gvec4[_TItem]: ...
    @property
    def tstp(self) -> gvec4[_TItem]: ...
    @property
    def tsps(self) -> gvec4[_TItem]: ...
    @property
    def tspt(self) -> gvec4[_TItem]: ...
    @property
    def tspp(self) -> gvec4[_TItem]: ...
    @property
    def ttss(self) -> gvec4[_TItem]: ...
    @property
    def ttst(self) -> gvec4[_TItem]: ...
    @property
    def ttsp(self) -> gvec4[_TItem]: ...
    @property
    def ttts(self) -> gvec4[_TItem]: ...
    @property
    def tttt(self) -> gvec4[_TItem]: ...
    @property
    def tttp(self) -> gvec4[_TItem]: ...
    @property
    def ttps(self) -> gvec4[_TItem]: ...
    @property
    def ttpt(self) -> gvec4[_TItem]: ...
    @property
    def ttpp(self) -> gvec4[_TItem]: ...
    @property
    def tpss(self) -> gvec4[_TItem]: ...
    @property
    def tpst(self) -> gvec4[_TItem]: ...
    @property
    def tpsp(self) -> gvec4[_TItem]: ...
    @property
    def tpts(self) -> gvec4[_TItem]: ...
    @property
    def tptt(self) -> gvec4[_TItem]: ...
    @property
    def tptp(self) -> gvec4[_TItem]: ...
    @property
    def tpps(self) -> gvec4[_TItem]: ...
    @property
    def tppt(self) -> gvec4[_TItem]: ...
    @property
    def tppp(self) -> gvec4[_TItem]: ...
    @property
    def psss(self) -> gvec4[_TItem]: ...
    @property
    def psst(self) -> gvec4[_TItem]: ...
    @property
    def pssp(self) -> gvec4[_TItem]: ...
    @property
    def psts(self) -> gvec4[_TItem]: ...
    @property
    def pstt(self) -> gvec4[_TItem]: ...
    @property
    def pstp(self) -> gvec4[_TItem]: ...
    @property
    def psps(self) -> gvec4[_TItem]: ...
    @property
    def pspt(self) -> gvec4[_TItem]: ...
    @property
    def pspp(self) -> gvec4[_TItem]: ...
    @property
    def ptss(self) -> gvec4[_TItem]: ...
    @property
    def ptst(self) -> gvec4[_TItem]: ...
    @property
    def ptsp(self) -> gvec4[_TItem]: ...
    @property
    def ptts(self) -> gvec4[_TItem]: ...
    @property
    def pttt(self) -> gvec4[_TItem]: ...
    @property
    def pttp(self) -> gvec4[_TItem]: ...
    @property
    def ptps(self) -> gvec4[_TItem]: ...
    @property
    def ptpt(self) -> gvec4[_TItem]: ...
    @property
    def ptpp(self) -> gvec4[_TItem]: ...
    @property
    def ppss(self) -> gvec4[_TItem]: ...
    @property
    def ppst(self) -> gvec4[_TItem]: ...
    @property
    def ppsp(self) -> gvec4[_TItem]: ...
    @property
    def ppts(self) -> gvec4[_TItem]: ...
    @property
    def pptt(self) -> gvec4[_TItem]: ...
    @property
    def pptp(self) -> gvec4[_TItem]: ...
    @property
    def ppps(self) -> gvec4[_TItem]: ...
    @property
    def pppt(self) -> gvec4[_TItem]: ...
    @property
    def pppp(self) -> gvec4[_TItem]: ...


@dataclass
class _4d_prop(tp.Generic[_TItem]):

    @property
    def x(self) -> _TItem: ...
    @x.setter
    def x(self, value: _TItem): ...
    @property
    def y(self) -> _TItem: ...
    @y.setter
    def y(self, value: _TItem): ...
    @property
    def z(self) -> _TItem: ...
    @z.setter
    def z(self, value: _TItem): ...
    @property
    def w(self) -> _TItem: ...
    @w.setter
    def w(self, value: _TItem): ...
    @property
    def xy(self) -> gvec2[_TItem]: ...
    @xy.setter
    def xy(self, value: gvec2[_TItem]): ...
    @property
    def xz(self) -> gvec2[_TItem]: ...
    @xz.setter
    def xz(self, value: gvec2[_TItem]): ...
    @property
    def xw(self) -> gvec2[_TItem]: ...
    @xw.setter
    def xw(self, value: gvec2[_TItem]): ...
    @property
    def yx(self) -> gvec2[_TItem]: ...
    @yx.setter
    def yx(self, value: gvec2[_TItem]): ...
    @property
    def yz(self) -> gvec2[_TItem]: ...
    @yz.setter
    def yz(self, value: gvec2[_TItem]): ...
    @property
    def yw(self) -> gvec2[_TItem]: ...
    @yw.setter
    def yw(self, value: gvec2[_TItem]): ...
    @property
    def zx(self) -> gvec2[_TItem]: ...
    @zx.setter
    def zx(self, value: gvec2[_TItem]): ...
    @property
    def zy(self) -> gvec2[_TItem]: ...
    @zy.setter
    def zy(self, value: gvec2[_TItem]): ...
    @property
    def zw(self) -> gvec2[_TItem]: ...
    @zw.setter
    def zw(self, value: gvec2[_TItem]): ...
    @property
    def wx(self) -> gvec2[_TItem]: ...
    @wx.setter
    def wx(self, value: gvec2[_TItem]): ...
    @property
    def wy(self) -> gvec2[_TItem]: ...
    @wy.setter
    def wy(self, value: gvec2[_TItem]): ...
    @property
    def wz(self) -> gvec2[_TItem]: ...
    @wz.setter
    def wz(self, value: gvec2[_TItem]): ...
    @property
    def xyz(self) -> gvec3[_TItem]: ...
    @xyz.setter
    def xyz(self, value: gvec3[_TItem]): ...
    @property
    def xyw(self) -> gvec3[_TItem]: ...
    @xyw.setter
    def xyw(self, value: gvec3[_TItem]): ...
    @property
    def xzy(self) -> gvec3[_TItem]: ...
    @xzy.setter
    def xzy(self, value: gvec3[_TItem]): ...
    @property
    def xzw(self) -> gvec3[_TItem]: ...
    @xzw.setter
    def xzw(self, value: gvec3[_TItem]): ...
    @property
    def xwy(self) -> gvec3[_TItem]: ...
    @xwy.setter
    def xwy(self, value: gvec3[_TItem]): ...
    @property
    def xwz(self) -> gvec3[_TItem]: ...
    @xwz.setter
    def xwz(self, value: gvec3[_TItem]): ...
    @property
    def yxz(self) -> gvec3[_TItem]: ...
    @yxz.setter
    def yxz(self, value: gvec3[_TItem]): ...
    @property
    def yxw(self) -> gvec3[_TItem]: ...
    @yxw.setter
    def yxw(self, value: gvec3[_TItem]): ...
    @property
    def yzx(self) -> gvec3[_TItem]: ...
    @yzx.setter
    def yzx(self, value: gvec3[_TItem]): ...
    @property
    def yzw(self) -> gvec3[_TItem]: ...
    @yzw.setter
    def yzw(self, value: gvec3[_TItem]): ...
    @property
    def ywx(self) -> gvec3[_TItem]: ...
    @ywx.setter
    def ywx(self, value: gvec3[_TItem]): ...
    @property
    def ywz(self) -> gvec3[_TItem]: ...
    @ywz.setter
    def ywz(self, value: gvec3[_TItem]): ...
    @property
    def zxy(self) -> gvec3[_TItem]: ...
    @zxy.setter
    def zxy(self, value: gvec3[_TItem]): ...
    @property
    def zxw(self) -> gvec3[_TItem]: ...
    @zxw.setter
    def zxw(self, value: gvec3[_TItem]): ...
    @property
    def zyx(self) -> gvec3[_TItem]: ...
    @zyx.setter
    def zyx(self, value: gvec3[_TItem]): ...
    @property
    def zyw(self) -> gvec3[_TItem]: ...
    @zyw.setter
    def zyw(self, value: gvec3[_TItem]): ...
    @property
    def zwx(self) -> gvec3[_TItem]: ...
    @zwx.setter
    def zwx(self, value: gvec3[_TItem]): ...
    @property
    def zwy(self) -> gvec3[_TItem]: ...
    @zwy.setter
    def zwy(self, value: gvec3[_TItem]): ...
    @property
    def wxy(self) -> gvec3[_TItem]: ...
    @wxy.setter
    def wxy(self, value: gvec3[_TItem]): ...
    @property
    def wxz(self) -> gvec3[_TItem]: ...
    @wxz.setter
    def wxz(self, value: gvec3[_TItem]): ...
    @property
    def wyx(self) -> gvec3[_TItem]: ...
    @wyx.setter
    def wyx(self, value: gvec3[_TItem]): ...
    @property
    def wyz(self) -> gvec3[_TItem]: ...
    @wyz.setter
    def wyz(self, value: gvec3[_TItem]): ...
    @property
    def wzx(self) -> gvec3[_TItem]: ...
    @wzx.setter
    def wzx(self, value: gvec3[_TItem]): ...
    @property
    def wzy(self) -> gvec3[_TItem]: ...
    @wzy.setter
    def wzy(self, value: gvec3[_TItem]): ...
    @property
    def xyzw(self) -> gvec4[_TItem]: ...
    @xyzw.setter
    def xyzw(self, value: gvec4[_TItem]): ...
    @property
    def xywz(self) -> gvec4[_TItem]: ...
    @xywz.setter
    def xywz(self, value: gvec4[_TItem]): ...
    @property
    def xzyw(self) -> gvec4[_TItem]: ...
    @xzyw.setter
    def xzyw(self, value: gvec4[_TItem]): ...
    @property
    def xzwy(self) -> gvec4[_TItem]: ...
    @xzwy.setter
    def xzwy(self, value: gvec4[_TItem]): ...
    @property
    def xwyz(self) -> gvec4[_TItem]: ...
    @xwyz.setter
    def xwyz(self, value: gvec4[_TItem]): ...
    @property
    def xwzy(self) -> gvec4[_TItem]: ...
    @xwzy.setter
    def xwzy(self, value: gvec4[_TItem]): ...
    @property
    def yxzw(self) -> gvec4[_TItem]: ...
    @yxzw.setter
    def yxzw(self, value: gvec4[_TItem]): ...
    @property
    def yxwz(self) -> gvec4[_TItem]: ...
    @yxwz.setter
    def yxwz(self, value: gvec4[_TItem]): ...
    @property
    def yzxw(self) -> gvec4[_TItem]: ...
    @yzxw.setter
    def yzxw(self, value: gvec4[_TItem]): ...
    @property
    def yzwx(self) -> gvec4[_TItem]: ...
    @yzwx.setter
    def yzwx(self, value: gvec4[_TItem]): ...
    @property
    def ywxz(self) -> gvec4[_TItem]: ...
    @ywxz.setter
    def ywxz(self, value: gvec4[_TItem]): ...
    @property
    def ywzx(self) -> gvec4[_TItem]: ...
    @ywzx.setter
    def ywzx(self, value: gvec4[_TItem]): ...
    @property
    def zxyw(self) -> gvec4[_TItem]: ...
    @zxyw.setter
    def zxyw(self, value: gvec4[_TItem]): ...
    @property
    def zxwy(self) -> gvec4[_TItem]: ...
    @zxwy.setter
    def zxwy(self, value: gvec4[_TItem]): ...
    @property
    def zyxw(self) -> gvec4[_TItem]: ...
    @zyxw.setter
    def zyxw(self, value: gvec4[_TItem]): ...
    @property
    def zywx(self) -> gvec4[_TItem]: ...
    @zywx.setter
    def zywx(self, value: gvec4[_TItem]): ...
    @property
    def zwxy(self) -> gvec4[_TItem]: ...
    @zwxy.setter
    def zwxy(self, value: gvec4[_TItem]): ...
    @property
    def zwyx(self) -> gvec4[_TItem]: ...
    @zwyx.setter
    def zwyx(self, value: gvec4[_TItem]): ...
    @property
    def wxyz(self) -> gvec4[_TItem]: ...
    @wxyz.setter
    def wxyz(self, value: gvec4[_TItem]): ...
    @property
    def wxzy(self) -> gvec4[_TItem]: ...
    @wxzy.setter
    def wxzy(self, value: gvec4[_TItem]): ...
    @property
    def wyxz(self) -> gvec4[_TItem]: ...
    @wyxz.setter
    def wyxz(self, value: gvec4[_TItem]): ...
    @property
    def wyzx(self) -> gvec4[_TItem]: ...
    @wyzx.setter
    def wyzx(self, value: gvec4[_TItem]): ...
    @property
    def wzxy(self) -> gvec4[_TItem]: ...
    @wzxy.setter
    def wzxy(self, value: gvec4[_TItem]): ...
    @property
    def wzyx(self) -> gvec4[_TItem]: ...
    @wzyx.setter
    def wzyx(self, value: gvec4[_TItem]): ...
    @property
    def xx(self) -> gvec2[_TItem]: ...
    @property
    def yy(self) -> gvec2[_TItem]: ...
    @property
    def zz(self) -> gvec2[_TItem]: ...
    @property
    def ww(self) -> gvec2[_TItem]: ...
    @property
    def xxx(self) -> gvec3[_TItem]: ...
    @property
    def xxy(self) -> gvec3[_TItem]: ...
    @property
    def xxz(self) -> gvec3[_TItem]: ...
    @property
    def xxw(self) -> gvec3[_TItem]: ...
    @property
    def xyx(self) -> gvec3[_TItem]: ...
    @property
    def xyy(self) -> gvec3[_TItem]: ...
    @property
    def xzx(self) -> gvec3[_TItem]: ...
    @property
    def xzz(self) -> gvec3[_TItem]: ...
    @property
    def xwx(self) -> gvec3[_TItem]: ...
    @property
    def xww(self) -> gvec3[_TItem]: ...
    @property
    def yxx(self) -> gvec3[_TItem]: ...
    @property
    def yxy(self) -> gvec3[_TItem]: ...
    @property
    def yyx(self) -> gvec3[_TItem]: ...
    @property
    def yyy(self) -> gvec3[_TItem]: ...
    @property
    def yyz(self) -> gvec3[_TItem]: ...
    @property
    def yyw(self) -> gvec3[_TItem]: ...
    @property
    def yzy(self) -> gvec3[_TItem]: ...
    @property
    def yzz(self) -> gvec3[_TItem]: ...
    @property
    def ywy(self) -> gvec3[_TItem]: ...
    @property
    def yww(self) -> gvec3[_TItem]: ...
    @property
    def zxx(self) -> gvec3[_TItem]: ...
    @property
    def zxz(self) -> gvec3[_TItem]: ...
    @property
    def zyy(self) -> gvec3[_TItem]: ...
    @property
    def zyz(self) -> gvec3[_TItem]: ...
    @property
    def zzx(self) -> gvec3[_TItem]: ...
    @property
    def zzy(self) -> gvec3[_TItem]: ...
    @property
    def zzz(self) -> gvec3[_TItem]: ...
    @property
    def zzw(self) -> gvec3[_TItem]: ...
    @property
    def zwz(self) -> gvec3[_TItem]: ...
    @property
    def zww(self) -> gvec3[_TItem]: ...
    @property
    def wxx(self) -> gvec3[_TItem]: ...
    @property
    def wxw(self) -> gvec3[_TItem]: ...
    @property
    def wyy(self) -> gvec3[_TItem]: ...
    @property
    def wyw(self) -> gvec3[_TItem]: ...
    @property
    def wzz(self) -> gvec3[_TItem]: ...
    @property
    def wzw(self) -> gvec3[_TItem]: ...
    @property
    def wwx(self) -> gvec3[_TItem]: ...
    @property
    def wwy(self) -> gvec3[_TItem]: ...
    @property
    def wwz(self) -> gvec3[_TItem]: ...
    @property
    def www(self) -> gvec3[_TItem]: ...
    @property
    def xxxx(self) -> gvec4[_TItem]: ...
    @property
    def xxxy(self) -> gvec4[_TItem]: ...
    @property
    def xxxz(self) -> gvec4[_TItem]: ...
    @property
    def xxxw(self) -> gvec4[_TItem]: ...
    @property
    def xxyx(self) -> gvec4[_TItem]: ...
    @property
    def xxyy(self) -> gvec4[_TItem]: ...
    @property
    def xxyz(self) -> gvec4[_TItem]: ...
    @property
    def xxyw(self) -> gvec4[_TItem]: ...
    @property
    def xxzx(self) -> gvec4[_TItem]: ...
    @property
    def xxzy(self) -> gvec4[_TItem]: ...
    @property
    def xxzz(self) -> gvec4[_TItem]: ...
    @property
    def xxzw(self) -> gvec4[_TItem]: ...
    @property
    def xxwx(self) -> gvec4[_TItem]: ...
    @property
    def xxwy(self) -> gvec4[_TItem]: ...
    @property
    def xxwz(self) -> gvec4[_TItem]: ...
    @property
    def xxww(self) -> gvec4[_TItem]: ...
    @property
    def xyxx(self) -> gvec4[_TItem]: ...
    @property
    def xyxy(self) -> gvec4[_TItem]: ...
    @property
    def xyxz(self) -> gvec4[_TItem]: ...
    @property
    def xyxw(self) -> gvec4[_TItem]: ...
    @property
    def xyyx(self) -> gvec4[_TItem]: ...
    @property
    def xyyy(self) -> gvec4[_TItem]: ...
    @property
    def xyyz(self) -> gvec4[_TItem]: ...
    @property
    def xyyw(self) -> gvec4[_TItem]: ...
    @property
    def xyzx(self) -> gvec4[_TItem]: ...
    @property
    def xyzy(self) -> gvec4[_TItem]: ...
    @property
    def xyzz(self) -> gvec4[_TItem]: ...
    @property
    def xywx(self) -> gvec4[_TItem]: ...
    @property
    def xywy(self) -> gvec4[_TItem]: ...
    @property
    def xyww(self) -> gvec4[_TItem]: ...
    @property
    def xzxx(self) -> gvec4[_TItem]: ...
    @property
    def xzxy(self) -> gvec4[_TItem]: ...
    @property
    def xzxz(self) -> gvec4[_TItem]: ...
    @property
    def xzxw(self) -> gvec4[_TItem]: ...
    @property
    def xzyx(self) -> gvec4[_TItem]: ...
    @property
    def xzyy(self) -> gvec4[_TItem]: ...
    @property
    def xzyz(self) -> gvec4[_TItem]: ...
    @property
    def xzzx(self) -> gvec4[_TItem]: ...
    @property
    def xzzy(self) -> gvec4[_TItem]: ...
    @property
    def xzzz(self) -> gvec4[_TItem]: ...
    @property
    def xzzw(self) -> gvec4[_TItem]: ...
    @property
    def xzwx(self) -> gvec4[_TItem]: ...
    @property
    def xzwz(self) -> gvec4[_TItem]: ...
    @property
    def xzww(self) -> gvec4[_TItem]: ...
    @property
    def xwxx(self) -> gvec4[_TItem]: ...
    @property
    def xwxy(self) -> gvec4[_TItem]: ...
    @property
    def xwxz(self) -> gvec4[_TItem]: ...
    @property
    def xwxw(self) -> gvec4[_TItem]: ...
    @property
    def xwyx(self) -> gvec4[_TItem]: ...
    @property
    def xwyy(self) -> gvec4[_TItem]: ...
    @property
    def xwyw(self) -> gvec4[_TItem]: ...
    @property
    def xwzx(self) -> gvec4[_TItem]: ...
    @property
    def xwzz(self) -> gvec4[_TItem]: ...
    @property
    def xwzw(self) -> gvec4[_TItem]: ...
    @property
    def xwwx(self) -> gvec4[_TItem]: ...
    @property
    def xwwy(self) -> gvec4[_TItem]: ...
    @property
    def xwwz(self) -> gvec4[_TItem]: ...
    @property
    def xwww(self) -> gvec4[_TItem]: ...
    @property
    def yxxx(self) -> gvec4[_TItem]: ...
    @property
    def yxxy(self) -> gvec4[_TItem]: ...
    @property
    def yxxz(self) -> gvec4[_TItem]: ...
    @property
    def yxxw(self) -> gvec4[_TItem]: ...
    @property
    def yxyx(self) -> gvec4[_TItem]: ...
    @property
    def yxyy(self) -> gvec4[_TItem]: ...
    @property
    def yxyz(self) -> gvec4[_TItem]: ...
    @property
    def yxyw(self) -> gvec4[_TItem]: ...
    @property
    def yxzx(self) -> gvec4[_TItem]: ...
    @property
    def yxzy(self) -> gvec4[_TItem]: ...
    @property
    def yxzz(self) -> gvec4[_TItem]: ...
    @property
    def yxwx(self) -> gvec4[_TItem]: ...
    @property
    def yxwy(self) -> gvec4[_TItem]: ...
    @property
    def yxww(self) -> gvec4[_TItem]: ...
    @property
    def yyxx(self) -> gvec4[_TItem]: ...
    @property
    def yyxy(self) -> gvec4[_TItem]: ...
    @property
    def yyxz(self) -> gvec4[_TItem]: ...
    @property
    def yyxw(self) -> gvec4[_TItem]: ...
    @property
    def yyyx(self) -> gvec4[_TItem]: ...
    @property
    def yyyy(self) -> gvec4[_TItem]: ...
    @property
    def yyyz(self) -> gvec4[_TItem]: ...
    @property
    def yyyw(self) -> gvec4[_TItem]: ...
    @property
    def yyzx(self) -> gvec4[_TItem]: ...
    @property
    def yyzy(self) -> gvec4[_TItem]: ...
    @property
    def yyzz(self) -> gvec4[_TItem]: ...
    @property
    def yyzw(self) -> gvec4[_TItem]: ...
    @property
    def yywx(self) -> gvec4[_TItem]: ...
    @property
    def yywy(self) -> gvec4[_TItem]: ...
    @property
    def yywz(self) -> gvec4[_TItem]: ...
    @property
    def yyww(self) -> gvec4[_TItem]: ...
    @property
    def yzxx(self) -> gvec4[_TItem]: ...
    @property
    def yzxy(self) -> gvec4[_TItem]: ...
    @property
    def yzxz(self) -> gvec4[_TItem]: ...
    @property
    def yzyx(self) -> gvec4[_TItem]: ...
    @property
    def yzyy(self) -> gvec4[_TItem]: ...
    @property
    def yzyz(self) -> gvec4[_TItem]: ...
    @property
    def yzyw(self) -> gvec4[_TItem]: ...
    @property
    def yzzx(self) -> gvec4[_TItem]: ...
    @property
    def yzzy(self) -> gvec4[_TItem]: ...
    @property
    def yzzz(self) -> gvec4[_TItem]: ...
    @property
    def yzzw(self) -> gvec4[_TItem]: ...
    @property
    def yzwy(self) -> gvec4[_TItem]: ...
    @property
    def yzwz(self) -> gvec4[_TItem]: ...
    @property
    def yzww(self) -> gvec4[_TItem]: ...
    @property
    def ywxx(self) -> gvec4[_TItem]: ...
    @property
    def ywxy(self) -> gvec4[_TItem]: ...
    @property
    def ywxw(self) -> gvec4[_TItem]: ...
    @property
    def ywyx(self) -> gvec4[_TItem]: ...
    @property
    def ywyy(self) -> gvec4[_TItem]: ...
    @property
    def ywyz(self) -> gvec4[_TItem]: ...
    @property
    def ywyw(self) -> gvec4[_TItem]: ...
    @property
    def ywzy(self) -> gvec4[_TItem]: ...
    @property
    def ywzz(self) -> gvec4[_TItem]: ...
    @property
    def ywzw(self) -> gvec4[_TItem]: ...
    @property
    def ywwx(self) -> gvec4[_TItem]: ...
    @property
    def ywwy(self) -> gvec4[_TItem]: ...
    @property
    def ywwz(self) -> gvec4[_TItem]: ...
    @property
    def ywww(self) -> gvec4[_TItem]: ...
    @property
    def zxxx(self) -> gvec4[_TItem]: ...
    @property
    def zxxy(self) -> gvec4[_TItem]: ...
    @property
    def zxxz(self) -> gvec4[_TItem]: ...
    @property
    def zxxw(self) -> gvec4[_TItem]: ...
    @property
    def zxyx(self) -> gvec4[_TItem]: ...
    @property
    def zxyy(self) -> gvec4[_TItem]: ...
    @property
    def zxyz(self) -> gvec4[_TItem]: ...
    @property
    def zxzx(self) -> gvec4[_TItem]: ...
    @property
    def zxzy(self) -> gvec4[_TItem]: ...
    @property
    def zxzz(self) -> gvec4[_TItem]: ...
    @property
    def zxzw(self) -> gvec4[_TItem]: ...
    @property
    def zxwx(self) -> gvec4[_TItem]: ...
    @property
    def zxwz(self) -> gvec4[_TItem]: ...
    @property
    def zxww(self) -> gvec4[_TItem]: ...
    @property
    def zyxx(self) -> gvec4[_TItem]: ...
    @property
    def zyxy(self) -> gvec4[_TItem]: ...
    @property
    def zyxz(self) -> gvec4[_TItem]: ...
    @property
    def zyyx(self) -> gvec4[_TItem]: ...
    @property
    def zyyy(self) -> gvec4[_TItem]: ...
    @property
    def zyyz(self) -> gvec4[_TItem]: ...
    @property
    def zyyw(self) -> gvec4[_TItem]: ...
    @property
    def zyzx(self) -> gvec4[_TItem]: ...
    @property
    def zyzy(self) -> gvec4[_TItem]: ...
    @property
    def zyzz(self) -> gvec4[_TItem]: ...
    @property
    def zyzw(self) -> gvec4[_TItem]: ...
    @property
    def zywy(self) -> gvec4[_TItem]: ...
    @property
    def zywz(self) -> gvec4[_TItem]: ...
    @property
    def zyww(self) -> gvec4[_TItem]: ...
    @property
    def zzxx(self) -> gvec4[_TItem]: ...
    @property
    def zzxy(self) -> gvec4[_TItem]: ...
    @property
    def zzxz(self) -> gvec4[_TItem]: ...
    @property
    def zzxw(self) -> gvec4[_TItem]: ...
    @property
    def zzyx(self) -> gvec4[_TItem]: ...
    @property
    def zzyy(self) -> gvec4[_TItem]: ...
    @property
    def zzyz(self) -> gvec4[_TItem]: ...
    @property
    def zzyw(self) -> gvec4[_TItem]: ...
    @property
    def zzzx(self) -> gvec4[_TItem]: ...
    @property
    def zzzy(self) -> gvec4[_TItem]: ...
    @property
    def zzzz(self) -> gvec4[_TItem]: ...
    @property
    def zzzw(self) -> gvec4[_TItem]: ...
    @property
    def zzwx(self) -> gvec4[_TItem]: ...
    @property
    def zzwy(self) -> gvec4[_TItem]: ...
    @property
    def zzwz(self) -> gvec4[_TItem]: ...
    @property
    def zzww(self) -> gvec4[_TItem]: ...
    @property
    def zwxx(self) -> gvec4[_TItem]: ...
    @property
    def zwxz(self) -> gvec4[_TItem]: ...
    @property
    def zwxw(self) -> gvec4[_TItem]: ...
    @property
    def zwyy(self) -> gvec4[_TItem]: ...
    @property
    def zwyz(self) -> gvec4[_TItem]: ...
    @property
    def zwyw(self) -> gvec4[_TItem]: ...
    @property
    def zwzx(self) -> gvec4[_TItem]: ...
    @property
    def zwzy(self) -> gvec4[_TItem]: ...
    @property
    def zwzz(self) -> gvec4[_TItem]: ...
    @property
    def zwzw(self) -> gvec4[_TItem]: ...
    @property
    def zwwx(self) -> gvec4[_TItem]: ...
    @property
    def zwwy(self) -> gvec4[_TItem]: ...
    @property
    def zwwz(self) -> gvec4[_TItem]: ...
    @property
    def zwww(self) -> gvec4[_TItem]: ...
    @property
    def wxxx(self) -> gvec4[_TItem]: ...
    @property
    def wxxy(self) -> gvec4[_TItem]: ...
    @property
    def wxxz(self) -> gvec4[_TItem]: ...
    @property
    def wxxw(self) -> gvec4[_TItem]: ...
    @property
    def wxyx(self) -> gvec4[_TItem]: ...
    @property
    def wxyy(self) -> gvec4[_TItem]: ...
    @property
    def wxyw(self) -> gvec4[_TItem]: ...
    @property
    def wxzx(self) -> gvec4[_TItem]: ...
    @property
    def wxzz(self) -> gvec4[_TItem]: ...
    @property
    def wxzw(self) -> gvec4[_TItem]: ...
    @property
    def wxwx(self) -> gvec4[_TItem]: ...
    @property
    def wxwy(self) -> gvec4[_TItem]: ...
    @property
    def wxwz(self) -> gvec4[_TItem]: ...
    @property
    def wxww(self) -> gvec4[_TItem]: ...
    @property
    def wyxx(self) -> gvec4[_TItem]: ...
    @property
    def wyxy(self) -> gvec4[_TItem]: ...
    @property
    def wyxw(self) -> gvec4[_TItem]: ...
    @property
    def wyyx(self) -> gvec4[_TItem]: ...
    @property
    def wyyy(self) -> gvec4[_TItem]: ...
    @property
    def wyyz(self) -> gvec4[_TItem]: ...
    @property
    def wyyw(self) -> gvec4[_TItem]: ...
    @property
    def wyzy(self) -> gvec4[_TItem]: ...
    @property
    def wyzz(self) -> gvec4[_TItem]: ...
    @property
    def wyzw(self) -> gvec4[_TItem]: ...
    @property
    def wywx(self) -> gvec4[_TItem]: ...
    @property
    def wywy(self) -> gvec4[_TItem]: ...
    @property
    def wywz(self) -> gvec4[_TItem]: ...
    @property
    def wyww(self) -> gvec4[_TItem]: ...
    @property
    def wzxx(self) -> gvec4[_TItem]: ...
    @property
    def wzxz(self) -> gvec4[_TItem]: ...
    @property
    def wzxw(self) -> gvec4[_TItem]: ...
    @property
    def wzyy(self) -> gvec4[_TItem]: ...
    @property
    def wzyz(self) -> gvec4[_TItem]: ...
    @property
    def wzyw(self) -> gvec4[_TItem]: ...
    @property
    def wzzx(self) -> gvec4[_TItem]: ...
    @property
    def wzzy(self) -> gvec4[_TItem]: ...
    @property
    def wzzz(self) -> gvec4[_TItem]: ...
    @property
    def wzzw(self) -> gvec4[_TItem]: ...
    @property
    def wzwx(self) -> gvec4[_TItem]: ...
    @property
    def wzwy(self) -> gvec4[_TItem]: ...
    @property
    def wzwz(self) -> gvec4[_TItem]: ...
    @property
    def wzww(self) -> gvec4[_TItem]: ...
    @property
    def wwxx(self) -> gvec4[_TItem]: ...
    @property
    def wwxy(self) -> gvec4[_TItem]: ...
    @property
    def wwxz(self) -> gvec4[_TItem]: ...
    @property
    def wwxw(self) -> gvec4[_TItem]: ...
    @property
    def wwyx(self) -> gvec4[_TItem]: ...
    @property
    def wwyy(self) -> gvec4[_TItem]: ...
    @property
    def wwyz(self) -> gvec4[_TItem]: ...
    @property
    def wwyw(self) -> gvec4[_TItem]: ...
    @property
    def wwzx(self) -> gvec4[_TItem]: ...
    @property
    def wwzy(self) -> gvec4[_TItem]: ...
    @property
    def wwzz(self) -> gvec4[_TItem]: ...
    @property
    def wwzw(self) -> gvec4[_TItem]: ...
    @property
    def wwwx(self) -> gvec4[_TItem]: ...
    @property
    def wwwy(self) -> gvec4[_TItem]: ...
    @property
    def wwwz(self) -> gvec4[_TItem]: ...
    @property
    def wwww(self) -> gvec4[_TItem]: ...
    @property
    def r(self) -> _TItem: ...
    @r.setter
    def r(self, value: _TItem): ...
    @property
    def g(self) -> _TItem: ...
    @g.setter
    def g(self, value: _TItem): ...
    @property
    def b(self) -> _TItem: ...
    @b.setter
    def b(self, value: _TItem): ...
    @property
    def a(self) -> _TItem: ...
    @a.setter
    def a(self, value: _TItem): ...
    @property
    def rg(self) -> gvec2[_TItem]: ...
    @rg.setter
    def rg(self, value: gvec2[_TItem]): ...
    @property
    def rb(self) -> gvec2[_TItem]: ...
    @rb.setter
    def rb(self, value: gvec2[_TItem]): ...
    @property
    def ra(self) -> gvec2[_TItem]: ...
    @ra.setter
    def ra(self, value: gvec2[_TItem]): ...
    @property
    def gr(self) -> gvec2[_TItem]: ...
    @gr.setter
    def gr(self, value: gvec2[_TItem]): ...
    @property
    def gb(self) -> gvec2[_TItem]: ...
    @gb.setter
    def gb(self, value: gvec2[_TItem]): ...
    @property
    def ga(self) -> gvec2[_TItem]: ...
    @ga.setter
    def ga(self, value: gvec2[_TItem]): ...
    @property
    def br(self) -> gvec2[_TItem]: ...
    @br.setter
    def br(self, value: gvec2[_TItem]): ...
    @property
    def bg(self) -> gvec2[_TItem]: ...
    @bg.setter
    def bg(self, value: gvec2[_TItem]): ...
    @property
    def ba(self) -> gvec2[_TItem]: ...
    @ba.setter
    def ba(self, value: gvec2[_TItem]): ...
    @property
    def ar(self) -> gvec2[_TItem]: ...
    @ar.setter
    def ar(self, value: gvec2[_TItem]): ...
    @property
    def ag(self) -> gvec2[_TItem]: ...
    @ag.setter
    def ag(self, value: gvec2[_TItem]): ...
    @property
    def ab(self) -> gvec2[_TItem]: ...
    @ab.setter
    def ab(self, value: gvec2[_TItem]): ...
    @property
    def rgb(self) -> gvec3[_TItem]: ...
    @rgb.setter
    def rgb(self, value: gvec3[_TItem]): ...
    @property
    def rga(self) -> gvec3[_TItem]: ...
    @rga.setter
    def rga(self, value: gvec3[_TItem]): ...
    @property
    def rbg(self) -> gvec3[_TItem]: ...
    @rbg.setter
    def rbg(self, value: gvec3[_TItem]): ...
    @property
    def rba(self) -> gvec3[_TItem]: ...
    @rba.setter
    def rba(self, value: gvec3[_TItem]): ...
    @property
    def rag(self) -> gvec3[_TItem]: ...
    @rag.setter
    def rag(self, value: gvec3[_TItem]): ...
    @property
    def rab(self) -> gvec3[_TItem]: ...
    @rab.setter
    def rab(self, value: gvec3[_TItem]): ...
    @property
    def grb(self) -> gvec3[_TItem]: ...
    @grb.setter
    def grb(self, value: gvec3[_TItem]): ...
    @property
    def gra(self) -> gvec3[_TItem]: ...
    @gra.setter
    def gra(self, value: gvec3[_TItem]): ...
    @property
    def gbr(self) -> gvec3[_TItem]: ...
    @gbr.setter
    def gbr(self, value: gvec3[_TItem]): ...
    @property
    def gba(self) -> gvec3[_TItem]: ...
    @gba.setter
    def gba(self, value: gvec3[_TItem]): ...
    @property
    def gar(self) -> gvec3[_TItem]: ...
    @gar.setter
    def gar(self, value: gvec3[_TItem]): ...
    @property
    def gab(self) -> gvec3[_TItem]: ...
    @gab.setter
    def gab(self, value: gvec3[_TItem]): ...
    @property
    def brg(self) -> gvec3[_TItem]: ...
    @brg.setter
    def brg(self, value: gvec3[_TItem]): ...
    @property
    def bra(self) -> gvec3[_TItem]: ...
    @bra.setter
    def bra(self, value: gvec3[_TItem]): ...
    @property
    def bgr(self) -> gvec3[_TItem]: ...
    @bgr.setter
    def bgr(self, value: gvec3[_TItem]): ...
    @property
    def bga(self) -> gvec3[_TItem]: ...
    @bga.setter
    def bga(self, value: gvec3[_TItem]): ...
    @property
    def bar(self) -> gvec3[_TItem]: ...
    @bar.setter
    def bar(self, value: gvec3[_TItem]): ...
    @property
    def bag(self) -> gvec3[_TItem]: ...
    @bag.setter
    def bag(self, value: gvec3[_TItem]): ...
    @property
    def arg(self) -> gvec3[_TItem]: ...
    @arg.setter
    def arg(self, value: gvec3[_TItem]): ...
    @property
    def arb(self) -> gvec3[_TItem]: ...
    @arb.setter
    def arb(self, value: gvec3[_TItem]): ...
    @property
    def agr(self) -> gvec3[_TItem]: ...
    @agr.setter
    def agr(self, value: gvec3[_TItem]): ...
    @property
    def agb(self) -> gvec3[_TItem]: ...
    @agb.setter
    def agb(self, value: gvec3[_TItem]): ...
    @property
    def abr(self) -> gvec3[_TItem]: ...
    @abr.setter
    def abr(self, value: gvec3[_TItem]): ...
    @property
    def abg(self) -> gvec3[_TItem]: ...
    @abg.setter
    def abg(self, value: gvec3[_TItem]): ...
    @property
    def rgba(self) -> gvec4[_TItem]: ...
    @rgba.setter
    def rgba(self, value: gvec4[_TItem]): ...
    @property
    def rgab(self) -> gvec4[_TItem]: ...
    @rgab.setter
    def rgab(self, value: gvec4[_TItem]): ...
    @property
    def rbga(self) -> gvec4[_TItem]: ...
    @rbga.setter
    def rbga(self, value: gvec4[_TItem]): ...
    @property
    def rbag(self) -> gvec4[_TItem]: ...
    @rbag.setter
    def rbag(self, value: gvec4[_TItem]): ...
    @property
    def ragb(self) -> gvec4[_TItem]: ...
    @ragb.setter
    def ragb(self, value: gvec4[_TItem]): ...
    @property
    def rabg(self) -> gvec4[_TItem]: ...
    @rabg.setter
    def rabg(self, value: gvec4[_TItem]): ...
    @property
    def grba(self) -> gvec4[_TItem]: ...
    @grba.setter
    def grba(self, value: gvec4[_TItem]): ...
    @property
    def grab(self) -> gvec4[_TItem]: ...
    @grab.setter
    def grab(self, value: gvec4[_TItem]): ...
    @property
    def gbra(self) -> gvec4[_TItem]: ...
    @gbra.setter
    def gbra(self, value: gvec4[_TItem]): ...
    @property
    def gbar(self) -> gvec4[_TItem]: ...
    @gbar.setter
    def gbar(self, value: gvec4[_TItem]): ...
    @property
    def garb(self) -> gvec4[_TItem]: ...
    @garb.setter
    def garb(self, value: gvec4[_TItem]): ...
    @property
    def gabr(self) -> gvec4[_TItem]: ...
    @gabr.setter
    def gabr(self, value: gvec4[_TItem]): ...
    @property
    def brga(self) -> gvec4[_TItem]: ...
    @brga.setter
    def brga(self, value: gvec4[_TItem]): ...
    @property
    def brag(self) -> gvec4[_TItem]: ...
    @brag.setter
    def brag(self, value: gvec4[_TItem]): ...
    @property
    def bgra(self) -> gvec4[_TItem]: ...
    @bgra.setter
    def bgra(self, value: gvec4[_TItem]): ...
    @property
    def bgar(self) -> gvec4[_TItem]: ...
    @bgar.setter
    def bgar(self, value: gvec4[_TItem]): ...
    @property
    def barg(self) -> gvec4[_TItem]: ...
    @barg.setter
    def barg(self, value: gvec4[_TItem]): ...
    @property
    def bagr(self) -> gvec4[_TItem]: ...
    @bagr.setter
    def bagr(self, value: gvec4[_TItem]): ...
    @property
    def argb(self) -> gvec4[_TItem]: ...
    @argb.setter
    def argb(self, value: gvec4[_TItem]): ...
    @property
    def arbg(self) -> gvec4[_TItem]: ...
    @arbg.setter
    def arbg(self, value: gvec4[_TItem]): ...
    @property
    def agrb(self) -> gvec4[_TItem]: ...
    @agrb.setter
    def agrb(self, value: gvec4[_TItem]): ...
    @property
    def agbr(self) -> gvec4[_TItem]: ...
    @agbr.setter
    def agbr(self, value: gvec4[_TItem]): ...
    @property
    def abrg(self) -> gvec4[_TItem]: ...
    @abrg.setter
    def abrg(self, value: gvec4[_TItem]): ...
    @property
    def abgr(self) -> gvec4[_TItem]: ...
    @abgr.setter
    def abgr(self, value: gvec4[_TItem]): ...
    @property
    def rr(self) -> gvec2[_TItem]: ...
    @property
    def gg(self) -> gvec2[_TItem]: ...
    @property
    def bb(self) -> gvec2[_TItem]: ...
    @property
    def aa(self) -> gvec2[_TItem]: ...
    @property
    def rrr(self) -> gvec3[_TItem]: ...
    @property
    def rrg(self) -> gvec3[_TItem]: ...
    @property
    def rrb(self) -> gvec3[_TItem]: ...
    @property
    def rra(self) -> gvec3[_TItem]: ...
    @property
    def rgr(self) -> gvec3[_TItem]: ...
    @property
    def rgg(self) -> gvec3[_TItem]: ...
    @property
    def rbr(self) -> gvec3[_TItem]: ...
    @property
    def rbb(self) -> gvec3[_TItem]: ...
    @property
    def rar(self) -> gvec3[_TItem]: ...
    @property
    def raa(self) -> gvec3[_TItem]: ...
    @property
    def grr(self) -> gvec3[_TItem]: ...
    @property
    def grg(self) -> gvec3[_TItem]: ...
    @property
    def ggr(self) -> gvec3[_TItem]: ...
    @property
    def ggg(self) -> gvec3[_TItem]: ...
    @property
    def ggb(self) -> gvec3[_TItem]: ...
    @property
    def gga(self) -> gvec3[_TItem]: ...
    @property
    def gbg(self) -> gvec3[_TItem]: ...
    @property
    def gbb(self) -> gvec3[_TItem]: ...
    @property
    def gag(self) -> gvec3[_TItem]: ...
    @property
    def gaa(self) -> gvec3[_TItem]: ...
    @property
    def brr(self) -> gvec3[_TItem]: ...
    @property
    def brb(self) -> gvec3[_TItem]: ...
    @property
    def bgg(self) -> gvec3[_TItem]: ...
    @property
    def bgb(self) -> gvec3[_TItem]: ...
    @property
    def bbr(self) -> gvec3[_TItem]: ...
    @property
    def bbg(self) -> gvec3[_TItem]: ...
    @property
    def bbb(self) -> gvec3[_TItem]: ...
    @property
    def bba(self) -> gvec3[_TItem]: ...
    @property
    def bab(self) -> gvec3[_TItem]: ...
    @property
    def baa(self) -> gvec3[_TItem]: ...
    @property
    def arr(self) -> gvec3[_TItem]: ...
    @property
    def ara(self) -> gvec3[_TItem]: ...
    @property
    def agg(self) -> gvec3[_TItem]: ...
    @property
    def aga(self) -> gvec3[_TItem]: ...
    @property
    def abb(self) -> gvec3[_TItem]: ...
    @property
    def aba(self) -> gvec3[_TItem]: ...
    @property
    def aar(self) -> gvec3[_TItem]: ...
    @property
    def aag(self) -> gvec3[_TItem]: ...
    @property
    def aab(self) -> gvec3[_TItem]: ...
    @property
    def aaa(self) -> gvec3[_TItem]: ...
    @property
    def rrrr(self) -> gvec4[_TItem]: ...
    @property
    def rrrg(self) -> gvec4[_TItem]: ...
    @property
    def rrrb(self) -> gvec4[_TItem]: ...
    @property
    def rrra(self) -> gvec4[_TItem]: ...
    @property
    def rrgr(self) -> gvec4[_TItem]: ...
    @property
    def rrgg(self) -> gvec4[_TItem]: ...
    @property
    def rrgb(self) -> gvec4[_TItem]: ...
    @property
    def rrga(self) -> gvec4[_TItem]: ...
    @property
    def rrbr(self) -> gvec4[_TItem]: ...
    @property
    def rrbg(self) -> gvec4[_TItem]: ...
    @property
    def rrbb(self) -> gvec4[_TItem]: ...
    @property
    def rrba(self) -> gvec4[_TItem]: ...
    @property
    def rrar(self) -> gvec4[_TItem]: ...
    @property
    def rrag(self) -> gvec4[_TItem]: ...
    @property
    def rrab(self) -> gvec4[_TItem]: ...
    @property
    def rraa(self) -> gvec4[_TItem]: ...
    @property
    def rgrr(self) -> gvec4[_TItem]: ...
    @property
    def rgrg(self) -> gvec4[_TItem]: ...
    @property
    def rgrb(self) -> gvec4[_TItem]: ...
    @property
    def rgra(self) -> gvec4[_TItem]: ...
    @property
    def rggr(self) -> gvec4[_TItem]: ...
    @property
    def rggg(self) -> gvec4[_TItem]: ...
    @property
    def rggb(self) -> gvec4[_TItem]: ...
    @property
    def rgga(self) -> gvec4[_TItem]: ...
    @property
    def rgbr(self) -> gvec4[_TItem]: ...
    @property
    def rgbg(self) -> gvec4[_TItem]: ...
    @property
    def rgbb(self) -> gvec4[_TItem]: ...
    @property
    def rgar(self) -> gvec4[_TItem]: ...
    @property
    def rgag(self) -> gvec4[_TItem]: ...
    @property
    def rgaa(self) -> gvec4[_TItem]: ...
    @property
    def rbrr(self) -> gvec4[_TItem]: ...
    @property
    def rbrg(self) -> gvec4[_TItem]: ...
    @property
    def rbrb(self) -> gvec4[_TItem]: ...
    @property
    def rbra(self) -> gvec4[_TItem]: ...
    @property
    def rbgr(self) -> gvec4[_TItem]: ...
    @property
    def rbgg(self) -> gvec4[_TItem]: ...
    @property
    def rbgb(self) -> gvec4[_TItem]: ...
    @property
    def rbbr(self) -> gvec4[_TItem]: ...
    @property
    def rbbg(self) -> gvec4[_TItem]: ...
    @property
    def rbbb(self) -> gvec4[_TItem]: ...
    @property
    def rbba(self) -> gvec4[_TItem]: ...
    @property
    def rbar(self) -> gvec4[_TItem]: ...
    @property
    def rbab(self) -> gvec4[_TItem]: ...
    @property
    def rbaa(self) -> gvec4[_TItem]: ...
    @property
    def rarr(self) -> gvec4[_TItem]: ...
    @property
    def rarg(self) -> gvec4[_TItem]: ...
    @property
    def rarb(self) -> gvec4[_TItem]: ...
    @property
    def rara(self) -> gvec4[_TItem]: ...
    @property
    def ragr(self) -> gvec4[_TItem]: ...
    @property
    def ragg(self) -> gvec4[_TItem]: ...
    @property
    def raga(self) -> gvec4[_TItem]: ...
    @property
    def rabr(self) -> gvec4[_TItem]: ...
    @property
    def rabb(self) -> gvec4[_TItem]: ...
    @property
    def raba(self) -> gvec4[_TItem]: ...
    @property
    def raar(self) -> gvec4[_TItem]: ...
    @property
    def raag(self) -> gvec4[_TItem]: ...
    @property
    def raab(self) -> gvec4[_TItem]: ...
    @property
    def raaa(self) -> gvec4[_TItem]: ...
    @property
    def grrr(self) -> gvec4[_TItem]: ...
    @property
    def grrg(self) -> gvec4[_TItem]: ...
    @property
    def grrb(self) -> gvec4[_TItem]: ...
    @property
    def grra(self) -> gvec4[_TItem]: ...
    @property
    def grgr(self) -> gvec4[_TItem]: ...
    @property
    def grgg(self) -> gvec4[_TItem]: ...
    @property
    def grgb(self) -> gvec4[_TItem]: ...
    @property
    def grga(self) -> gvec4[_TItem]: ...
    @property
    def grbr(self) -> gvec4[_TItem]: ...
    @property
    def grbg(self) -> gvec4[_TItem]: ...
    @property
    def grbb(self) -> gvec4[_TItem]: ...
    @property
    def grar(self) -> gvec4[_TItem]: ...
    @property
    def grag(self) -> gvec4[_TItem]: ...
    @property
    def graa(self) -> gvec4[_TItem]: ...
    @property
    def ggrr(self) -> gvec4[_TItem]: ...
    @property
    def ggrg(self) -> gvec4[_TItem]: ...
    @property
    def ggrb(self) -> gvec4[_TItem]: ...
    @property
    def ggra(self) -> gvec4[_TItem]: ...
    @property
    def gggr(self) -> gvec4[_TItem]: ...
    @property
    def gggg(self) -> gvec4[_TItem]: ...
    @property
    def gggb(self) -> gvec4[_TItem]: ...
    @property
    def ggga(self) -> gvec4[_TItem]: ...
    @property
    def ggbr(self) -> gvec4[_TItem]: ...
    @property
    def ggbg(self) -> gvec4[_TItem]: ...
    @property
    def ggbb(self) -> gvec4[_TItem]: ...
    @property
    def ggba(self) -> gvec4[_TItem]: ...
    @property
    def ggar(self) -> gvec4[_TItem]: ...
    @property
    def ggag(self) -> gvec4[_TItem]: ...
    @property
    def ggab(self) -> gvec4[_TItem]: ...
    @property
    def ggaa(self) -> gvec4[_TItem]: ...
    @property
    def gbrr(self) -> gvec4[_TItem]: ...
    @property
    def gbrg(self) -> gvec4[_TItem]: ...
    @property
    def gbrb(self) -> gvec4[_TItem]: ...
    @property
    def gbgr(self) -> gvec4[_TItem]: ...
    @property
    def gbgg(self) -> gvec4[_TItem]: ...
    @property
    def gbgb(self) -> gvec4[_TItem]: ...
    @property
    def gbga(self) -> gvec4[_TItem]: ...
    @property
    def gbbr(self) -> gvec4[_TItem]: ...
    @property
    def gbbg(self) -> gvec4[_TItem]: ...
    @property
    def gbbb(self) -> gvec4[_TItem]: ...
    @property
    def gbba(self) -> gvec4[_TItem]: ...
    @property
    def gbag(self) -> gvec4[_TItem]: ...
    @property
    def gbab(self) -> gvec4[_TItem]: ...
    @property
    def gbaa(self) -> gvec4[_TItem]: ...
    @property
    def garr(self) -> gvec4[_TItem]: ...
    @property
    def garg(self) -> gvec4[_TItem]: ...
    @property
    def gara(self) -> gvec4[_TItem]: ...
    @property
    def gagr(self) -> gvec4[_TItem]: ...
    @property
    def gagg(self) -> gvec4[_TItem]: ...
    @property
    def gagb(self) -> gvec4[_TItem]: ...
    @property
    def gaga(self) -> gvec4[_TItem]: ...
    @property
    def gabg(self) -> gvec4[_TItem]: ...
    @property
    def gabb(self) -> gvec4[_TItem]: ...
    @property
    def gaba(self) -> gvec4[_TItem]: ...
    @property
    def gaar(self) -> gvec4[_TItem]: ...
    @property
    def gaag(self) -> gvec4[_TItem]: ...
    @property
    def gaab(self) -> gvec4[_TItem]: ...
    @property
    def gaaa(self) -> gvec4[_TItem]: ...
    @property
    def brrr(self) -> gvec4[_TItem]: ...
    @property
    def brrg(self) -> gvec4[_TItem]: ...
    @property
    def brrb(self) -> gvec4[_TItem]: ...
    @property
    def brra(self) -> gvec4[_TItem]: ...
    @property
    def brgr(self) -> gvec4[_TItem]: ...
    @property
    def brgg(self) -> gvec4[_TItem]: ...
    @property
    def brgb(self) -> gvec4[_TItem]: ...
    @property
    def brbr(self) -> gvec4[_TItem]: ...
    @property
    def brbg(self) -> gvec4[_TItem]: ...
    @property
    def brbb(self) -> gvec4[_TItem]: ...
    @property
    def brba(self) -> gvec4[_TItem]: ...
    @property
    def brar(self) -> gvec4[_TItem]: ...
    @property
    def brab(self) -> gvec4[_TItem]: ...
    @property
    def braa(self) -> gvec4[_TItem]: ...
    @property
    def bgrr(self) -> gvec4[_TItem]: ...
    @property
    def bgrg(self) -> gvec4[_TItem]: ...
    @property
    def bgrb(self) -> gvec4[_TItem]: ...
    @property
    def bggr(self) -> gvec4[_TItem]: ...
    @property
    def bggg(self) -> gvec4[_TItem]: ...
    @property
    def bggb(self) -> gvec4[_TItem]: ...
    @property
    def bgga(self) -> gvec4[_TItem]: ...
    @property
    def bgbr(self) -> gvec4[_TItem]: ...
    @property
    def bgbg(self) -> gvec4[_TItem]: ...
    @property
    def bgbb(self) -> gvec4[_TItem]: ...
    @property
    def bgba(self) -> gvec4[_TItem]: ...
    @property
    def bgag(self) -> gvec4[_TItem]: ...
    @property
    def bgab(self) -> gvec4[_TItem]: ...
    @property
    def bgaa(self) -> gvec4[_TItem]: ...
    @property
    def bbrr(self) -> gvec4[_TItem]: ...
    @property
    def bbrg(self) -> gvec4[_TItem]: ...
    @property
    def bbrb(self) -> gvec4[_TItem]: ...
    @property
    def bbra(self) -> gvec4[_TItem]: ...
    @property
    def bbgr(self) -> gvec4[_TItem]: ...
    @property
    def bbgg(self) -> gvec4[_TItem]: ...
    @property
    def bbgb(self) -> gvec4[_TItem]: ...
    @property
    def bbga(self) -> gvec4[_TItem]: ...
    @property
    def bbbr(self) -> gvec4[_TItem]: ...
    @property
    def bbbg(self) -> gvec4[_TItem]: ...
    @property
    def bbbb(self) -> gvec4[_TItem]: ...
    @property
    def bbba(self) -> gvec4[_TItem]: ...
    @property
    def bbar(self) -> gvec4[_TItem]: ...
    @property
    def bbag(self) -> gvec4[_TItem]: ...
    @property
    def bbab(self) -> gvec4[_TItem]: ...
    @property
    def bbaa(self) -> gvec4[_TItem]: ...
    @property
    def barr(self) -> gvec4[_TItem]: ...
    @property
    def barb(self) -> gvec4[_TItem]: ...
    @property
    def bara(self) -> gvec4[_TItem]: ...
    @property
    def bagg(self) -> gvec4[_TItem]: ...
    @property
    def bagb(self) -> gvec4[_TItem]: ...
    @property
    def baga(self) -> gvec4[_TItem]: ...
    @property
    def babr(self) -> gvec4[_TItem]: ...
    @property
    def babg(self) -> gvec4[_TItem]: ...
    @property
    def babb(self) -> gvec4[_TItem]: ...
    @property
    def baba(self) -> gvec4[_TItem]: ...
    @property
    def baar(self) -> gvec4[_TItem]: ...
    @property
    def baag(self) -> gvec4[_TItem]: ...
    @property
    def baab(self) -> gvec4[_TItem]: ...
    @property
    def baaa(self) -> gvec4[_TItem]: ...
    @property
    def arrr(self) -> gvec4[_TItem]: ...
    @property
    def arrg(self) -> gvec4[_TItem]: ...
    @property
    def arrb(self) -> gvec4[_TItem]: ...
    @property
    def arra(self) -> gvec4[_TItem]: ...
    @property
    def argr(self) -> gvec4[_TItem]: ...
    @property
    def argg(self) -> gvec4[_TItem]: ...
    @property
    def arga(self) -> gvec4[_TItem]: ...
    @property
    def arbr(self) -> gvec4[_TItem]: ...
    @property
    def arbb(self) -> gvec4[_TItem]: ...
    @property
    def arba(self) -> gvec4[_TItem]: ...
    @property
    def arar(self) -> gvec4[_TItem]: ...
    @property
    def arag(self) -> gvec4[_TItem]: ...
    @property
    def arab(self) -> gvec4[_TItem]: ...
    @property
    def araa(self) -> gvec4[_TItem]: ...
    @property
    def agrr(self) -> gvec4[_TItem]: ...
    @property
    def agrg(self) -> gvec4[_TItem]: ...
    @property
    def agra(self) -> gvec4[_TItem]: ...
    @property
    def aggr(self) -> gvec4[_TItem]: ...
    @property
    def aggg(self) -> gvec4[_TItem]: ...
    @property
    def aggb(self) -> gvec4[_TItem]: ...
    @property
    def agga(self) -> gvec4[_TItem]: ...
    @property
    def agbg(self) -> gvec4[_TItem]: ...
    @property
    def agbb(self) -> gvec4[_TItem]: ...
    @property
    def agba(self) -> gvec4[_TItem]: ...
    @property
    def agar(self) -> gvec4[_TItem]: ...
    @property
    def agag(self) -> gvec4[_TItem]: ...
    @property
    def agab(self) -> gvec4[_TItem]: ...
    @property
    def agaa(self) -> gvec4[_TItem]: ...
    @property
    def abrr(self) -> gvec4[_TItem]: ...
    @property
    def abrb(self) -> gvec4[_TItem]: ...
    @property
    def abra(self) -> gvec4[_TItem]: ...
    @property
    def abgg(self) -> gvec4[_TItem]: ...
    @property
    def abgb(self) -> gvec4[_TItem]: ...
    @property
    def abga(self) -> gvec4[_TItem]: ...
    @property
    def abbr(self) -> gvec4[_TItem]: ...
    @property
    def abbg(self) -> gvec4[_TItem]: ...
    @property
    def abbb(self) -> gvec4[_TItem]: ...
    @property
    def abba(self) -> gvec4[_TItem]: ...
    @property
    def abar(self) -> gvec4[_TItem]: ...
    @property
    def abag(self) -> gvec4[_TItem]: ...
    @property
    def abab(self) -> gvec4[_TItem]: ...
    @property
    def abaa(self) -> gvec4[_TItem]: ...
    @property
    def aarr(self) -> gvec4[_TItem]: ...
    @property
    def aarg(self) -> gvec4[_TItem]: ...
    @property
    def aarb(self) -> gvec4[_TItem]: ...
    @property
    def aara(self) -> gvec4[_TItem]: ...
    @property
    def aagr(self) -> gvec4[_TItem]: ...
    @property
    def aagg(self) -> gvec4[_TItem]: ...
    @property
    def aagb(self) -> gvec4[_TItem]: ...
    @property
    def aaga(self) -> gvec4[_TItem]: ...
    @property
    def aabr(self) -> gvec4[_TItem]: ...
    @property
    def aabg(self) -> gvec4[_TItem]: ...
    @property
    def aabb(self) -> gvec4[_TItem]: ...
    @property
    def aaba(self) -> gvec4[_TItem]: ...
    @property
    def aaar(self) -> gvec4[_TItem]: ...
    @property
    def aaag(self) -> gvec4[_TItem]: ...
    @property
    def aaab(self) -> gvec4[_TItem]: ...
    @property
    def aaaa(self) -> gvec4[_TItem]: ...
    @property
    def s(self) -> _TItem: ...
    @s.setter
    def s(self, value: _TItem): ...
    @property
    def t(self) -> _TItem: ...
    @t.setter
    def t(self, value: _TItem): ...
    @property
    def p(self) -> _TItem: ...
    @p.setter
    def p(self, value: _TItem): ...
    @property
    def q(self) -> _TItem: ...
    @q.setter
    def q(self, value: _TItem): ...
    @property
    def st(self) -> gvec2[_TItem]: ...
    @st.setter
    def st(self, value: gvec2[_TItem]): ...
    @property
    def sp(self) -> gvec2[_TItem]: ...
    @sp.setter
    def sp(self, value: gvec2[_TItem]): ...
    @property
    def sq(self) -> gvec2[_TItem]: ...
    @sq.setter
    def sq(self, value: gvec2[_TItem]): ...
    @property
    def ts(self) -> gvec2[_TItem]: ...
    @ts.setter
    def ts(self, value: gvec2[_TItem]): ...
    @property
    def tp(self) -> gvec2[_TItem]: ...
    @tp.setter
    def tp(self, value: gvec2[_TItem]): ...
    @property
    def tq(self) -> gvec2[_TItem]: ...
    @tq.setter
    def tq(self, value: gvec2[_TItem]): ...
    @property
    def ps(self) -> gvec2[_TItem]: ...
    @ps.setter
    def ps(self, value: gvec2[_TItem]): ...
    @property
    def pt(self) -> gvec2[_TItem]: ...
    @pt.setter
    def pt(self, value: gvec2[_TItem]): ...
    @property
    def pq(self) -> gvec2[_TItem]: ...
    @pq.setter
    def pq(self, value: gvec2[_TItem]): ...
    @property
    def qs(self) -> gvec2[_TItem]: ...
    @qs.setter
    def qs(self, value: gvec2[_TItem]): ...
    @property
    def qt(self) -> gvec2[_TItem]: ...
    @qt.setter
    def qt(self, value: gvec2[_TItem]): ...
    @property
    def qp(self) -> gvec2[_TItem]: ...
    @qp.setter
    def qp(self, value: gvec2[_TItem]): ...
    @property
    def stp(self) -> gvec3[_TItem]: ...
    @stp.setter
    def stp(self, value: gvec3[_TItem]): ...
    @property
    def stq(self) -> gvec3[_TItem]: ...
    @stq.setter
    def stq(self, value: gvec3[_TItem]): ...
    @property
    def spt(self) -> gvec3[_TItem]: ...
    @spt.setter
    def spt(self, value: gvec3[_TItem]): ...
    @property
    def spq(self) -> gvec3[_TItem]: ...
    @spq.setter
    def spq(self, value: gvec3[_TItem]): ...
    @property
    def sqt(self) -> gvec3[_TItem]: ...
    @sqt.setter
    def sqt(self, value: gvec3[_TItem]): ...
    @property
    def sqp(self) -> gvec3[_TItem]: ...
    @sqp.setter
    def sqp(self, value: gvec3[_TItem]): ...
    @property
    def tsp(self) -> gvec3[_TItem]: ...
    @tsp.setter
    def tsp(self, value: gvec3[_TItem]): ...
    @property
    def tsq(self) -> gvec3[_TItem]: ...
    @tsq.setter
    def tsq(self, value: gvec3[_TItem]): ...
    @property
    def tps(self) -> gvec3[_TItem]: ...
    @tps.setter
    def tps(self, value: gvec3[_TItem]): ...
    @property
    def tpq(self) -> gvec3[_TItem]: ...
    @tpq.setter
    def tpq(self, value: gvec3[_TItem]): ...
    @property
    def tqs(self) -> gvec3[_TItem]: ...
    @tqs.setter
    def tqs(self, value: gvec3[_TItem]): ...
    @property
    def tqp(self) -> gvec3[_TItem]: ...
    @tqp.setter
    def tqp(self, value: gvec3[_TItem]): ...
    @property
    def pst(self) -> gvec3[_TItem]: ...
    @pst.setter
    def pst(self, value: gvec3[_TItem]): ...
    @property
    def psq(self) -> gvec3[_TItem]: ...
    @psq.setter
    def psq(self, value: gvec3[_TItem]): ...
    @property
    def pts(self) -> gvec3[_TItem]: ...
    @pts.setter
    def pts(self, value: gvec3[_TItem]): ...
    @property
    def ptq(self) -> gvec3[_TItem]: ...
    @ptq.setter
    def ptq(self, value: gvec3[_TItem]): ...
    @property
    def pqs(self) -> gvec3[_TItem]: ...
    @pqs.setter
    def pqs(self, value: gvec3[_TItem]): ...
    @property
    def pqt(self) -> gvec3[_TItem]: ...
    @pqt.setter
    def pqt(self, value: gvec3[_TItem]): ...
    @property
    def qst(self) -> gvec3[_TItem]: ...
    @qst.setter
    def qst(self, value: gvec3[_TItem]): ...
    @property
    def qsp(self) -> gvec3[_TItem]: ...
    @qsp.setter
    def qsp(self, value: gvec3[_TItem]): ...
    @property
    def qts(self) -> gvec3[_TItem]: ...
    @qts.setter
    def qts(self, value: gvec3[_TItem]): ...
    @property
    def qtp(self) -> gvec3[_TItem]: ...
    @qtp.setter
    def qtp(self, value: gvec3[_TItem]): ...
    @property
    def qps(self) -> gvec3[_TItem]: ...
    @qps.setter
    def qps(self, value: gvec3[_TItem]): ...
    @property
    def qpt(self) -> gvec3[_TItem]: ...
    @qpt.setter
    def qpt(self, value: gvec3[_TItem]): ...
    @property
    def stpq(self) -> gvec4[_TItem]: ...
    @stpq.setter
    def stpq(self, value: gvec4[_TItem]): ...
    @property
    def stqp(self) -> gvec4[_TItem]: ...
    @stqp.setter
    def stqp(self, value: gvec4[_TItem]): ...
    @property
    def sptq(self) -> gvec4[_TItem]: ...
    @sptq.setter
    def sptq(self, value: gvec4[_TItem]): ...
    @property
    def spqt(self) -> gvec4[_TItem]: ...
    @spqt.setter
    def spqt(self, value: gvec4[_TItem]): ...
    @property
    def sqtp(self) -> gvec4[_TItem]: ...
    @sqtp.setter
    def sqtp(self, value: gvec4[_TItem]): ...
    @property
    def sqpt(self) -> gvec4[_TItem]: ...
    @sqpt.setter
    def sqpt(self, value: gvec4[_TItem]): ...
    @property
    def tspq(self) -> gvec4[_TItem]: ...
    @tspq.setter
    def tspq(self, value: gvec4[_TItem]): ...
    @property
    def tsqp(self) -> gvec4[_TItem]: ...
    @tsqp.setter
    def tsqp(self, value: gvec4[_TItem]): ...
    @property
    def tpsq(self) -> gvec4[_TItem]: ...
    @tpsq.setter
    def tpsq(self, value: gvec4[_TItem]): ...
    @property
    def tpqs(self) -> gvec4[_TItem]: ...
    @tpqs.setter
    def tpqs(self, value: gvec4[_TItem]): ...
    @property
    def tqsp(self) -> gvec4[_TItem]: ...
    @tqsp.setter
    def tqsp(self, value: gvec4[_TItem]): ...
    @property
    def tqps(self) -> gvec4[_TItem]: ...
    @tqps.setter
    def tqps(self, value: gvec4[_TItem]): ...
    @property
    def pstq(self) -> gvec4[_TItem]: ...
    @pstq.setter
    def pstq(self, value: gvec4[_TItem]): ...
    @property
    def psqt(self) -> gvec4[_TItem]: ...
    @psqt.setter
    def psqt(self, value: gvec4[_TItem]): ...
    @property
    def ptsq(self) -> gvec4[_TItem]: ...
    @ptsq.setter
    def ptsq(self, value: gvec4[_TItem]): ...
    @property
    def ptqs(self) -> gvec4[_TItem]: ...
    @ptqs.setter
    def ptqs(self, value: gvec4[_TItem]): ...
    @property
    def pqst(self) -> gvec4[_TItem]: ...
    @pqst.setter
    def pqst(self, value: gvec4[_TItem]): ...
    @property
    def pqts(self) -> gvec4[_TItem]: ...
    @pqts.setter
    def pqts(self, value: gvec4[_TItem]): ...
    @property
    def qstp(self) -> gvec4[_TItem]: ...
    @qstp.setter
    def qstp(self, value: gvec4[_TItem]): ...
    @property
    def qspt(self) -> gvec4[_TItem]: ...
    @qspt.setter
    def qspt(self, value: gvec4[_TItem]): ...
    @property
    def qtsp(self) -> gvec4[_TItem]: ...
    @qtsp.setter
    def qtsp(self, value: gvec4[_TItem]): ...
    @property
    def qtps(self) -> gvec4[_TItem]: ...
    @qtps.setter
    def qtps(self, value: gvec4[_TItem]): ...
    @property
    def qpst(self) -> gvec4[_TItem]: ...
    @qpst.setter
    def qpst(self, value: gvec4[_TItem]): ...
    @property
    def qpts(self) -> gvec4[_TItem]: ...
    @qpts.setter
    def qpts(self, value: gvec4[_TItem]): ...
    @property
    def ss(self) -> gvec2[_TItem]: ...
    @property
    def tt(self) -> gvec2[_TItem]: ...
    @property
    def pp(self) -> gvec2[_TItem]: ...
    @property
    def qq(self) -> gvec2[_TItem]: ...
    @property
    def sss(self) -> gvec3[_TItem]: ...
    @property
    def sst(self) -> gvec3[_TItem]: ...
    @property
    def ssp(self) -> gvec3[_TItem]: ...
    @property
    def ssq(self) -> gvec3[_TItem]: ...
    @property
    def sts(self) -> gvec3[_TItem]: ...
    @property
    def stt(self) -> gvec3[_TItem]: ...
    @property
    def sps(self) -> gvec3[_TItem]: ...
    @property
    def spp(self) -> gvec3[_TItem]: ...
    @property
    def sqs(self) -> gvec3[_TItem]: ...
    @property
    def sqq(self) -> gvec3[_TItem]: ...
    @property
    def tss(self) -> gvec3[_TItem]: ...
    @property
    def tst(self) -> gvec3[_TItem]: ...
    @property
    def tts(self) -> gvec3[_TItem]: ...
    @property
    def ttt(self) -> gvec3[_TItem]: ...
    @property
    def ttp(self) -> gvec3[_TItem]: ...
    @property
    def ttq(self) -> gvec3[_TItem]: ...
    @property
    def tpt(self) -> gvec3[_TItem]: ...
    @property
    def tpp(self) -> gvec3[_TItem]: ...
    @property
    def tqt(self) -> gvec3[_TItem]: ...
    @property
    def tqq(self) -> gvec3[_TItem]: ...
    @property
    def pss(self) -> gvec3[_TItem]: ...
    @property
    def psp(self) -> gvec3[_TItem]: ...
    @property
    def ptt(self) -> gvec3[_TItem]: ...
    @property
    def ptp(self) -> gvec3[_TItem]: ...
    @property
    def pps(self) -> gvec3[_TItem]: ...
    @property
    def ppt(self) -> gvec3[_TItem]: ...
    @property
    def ppp(self) -> gvec3[_TItem]: ...
    @property
    def ppq(self) -> gvec3[_TItem]: ...
    @property
    def pqp(self) -> gvec3[_TItem]: ...
    @property
    def pqq(self) -> gvec3[_TItem]: ...
    @property
    def qss(self) -> gvec3[_TItem]: ...
    @property
    def qsq(self) -> gvec3[_TItem]: ...
    @property
    def qtt(self) -> gvec3[_TItem]: ...
    @property
    def qtq(self) -> gvec3[_TItem]: ...
    @property
    def qpp(self) -> gvec3[_TItem]: ...
    @property
    def qpq(self) -> gvec3[_TItem]: ...
    @property
    def qqs(self) -> gvec3[_TItem]: ...
    @property
    def qqt(self) -> gvec3[_TItem]: ...
    @property
    def qqp(self) -> gvec3[_TItem]: ...
    @property
    def qqq(self) -> gvec3[_TItem]: ...
    @property
    def ssss(self) -> gvec4[_TItem]: ...
    @property
    def ssst(self) -> gvec4[_TItem]: ...
    @property
    def sssp(self) -> gvec4[_TItem]: ...
    @property
    def sssq(self) -> gvec4[_TItem]: ...
    @property
    def ssts(self) -> gvec4[_TItem]: ...
    @property
    def sstt(self) -> gvec4[_TItem]: ...
    @property
    def sstp(self) -> gvec4[_TItem]: ...
    @property
    def sstq(self) -> gvec4[_TItem]: ...
    @property
    def ssps(self) -> gvec4[_TItem]: ...
    @property
    def sspt(self) -> gvec4[_TItem]: ...
    @property
    def sspp(self) -> gvec4[_TItem]: ...
    @property
    def sspq(self) -> gvec4[_TItem]: ...
    @property
    def ssqs(self) -> gvec4[_TItem]: ...
    @property
    def ssqt(self) -> gvec4[_TItem]: ...
    @property
    def ssqp(self) -> gvec4[_TItem]: ...
    @property
    def ssqq(self) -> gvec4[_TItem]: ...
    @property
    def stss(self) -> gvec4[_TItem]: ...
    @property
    def stst(self) -> gvec4[_TItem]: ...
    @property
    def stsp(self) -> gvec4[_TItem]: ...
    @property
    def stsq(self) -> gvec4[_TItem]: ...
    @property
    def stts(self) -> gvec4[_TItem]: ...
    @property
    def sttt(self) -> gvec4[_TItem]: ...
    @property
    def sttp(self) -> gvec4[_TItem]: ...
    @property
    def sttq(self) -> gvec4[_TItem]: ...
    @property
    def stps(self) -> gvec4[_TItem]: ...
    @property
    def stpt(self) -> gvec4[_TItem]: ...
    @property
    def stpp(self) -> gvec4[_TItem]: ...
    @property
    def stqs(self) -> gvec4[_TItem]: ...
    @property
    def stqt(self) -> gvec4[_TItem]: ...
    @property
    def stqq(self) -> gvec4[_TItem]: ...
    @property
    def spss(self) -> gvec4[_TItem]: ...
    @property
    def spst(self) -> gvec4[_TItem]: ...
    @property
    def spsp(self) -> gvec4[_TItem]: ...
    @property
    def spsq(self) -> gvec4[_TItem]: ...
    @property
    def spts(self) -> gvec4[_TItem]: ...
    @property
    def sptt(self) -> gvec4[_TItem]: ...
    @property
    def sptp(self) -> gvec4[_TItem]: ...
    @property
    def spps(self) -> gvec4[_TItem]: ...
    @property
    def sppt(self) -> gvec4[_TItem]: ...
    @property
    def sppp(self) -> gvec4[_TItem]: ...
    @property
    def sppq(self) -> gvec4[_TItem]: ...
    @property
    def spqs(self) -> gvec4[_TItem]: ...
    @property
    def spqp(self) -> gvec4[_TItem]: ...
    @property
    def spqq(self) -> gvec4[_TItem]: ...
    @property
    def sqss(self) -> gvec4[_TItem]: ...
    @property
    def sqst(self) -> gvec4[_TItem]: ...
    @property
    def sqsp(self) -> gvec4[_TItem]: ...
    @property
    def sqsq(self) -> gvec4[_TItem]: ...
    @property
    def sqts(self) -> gvec4[_TItem]: ...
    @property
    def sqtt(self) -> gvec4[_TItem]: ...
    @property
    def sqtq(self) -> gvec4[_TItem]: ...
    @property
    def sqps(self) -> gvec4[_TItem]: ...
    @property
    def sqpp(self) -> gvec4[_TItem]: ...
    @property
    def sqpq(self) -> gvec4[_TItem]: ...
    @property
    def sqqs(self) -> gvec4[_TItem]: ...
    @property
    def sqqt(self) -> gvec4[_TItem]: ...
    @property
    def sqqp(self) -> gvec4[_TItem]: ...
    @property
    def sqqq(self) -> gvec4[_TItem]: ...
    @property
    def tsss(self) -> gvec4[_TItem]: ...
    @property
    def tsst(self) -> gvec4[_TItem]: ...
    @property
    def tssp(self) -> gvec4[_TItem]: ...
    @property
    def tssq(self) -> gvec4[_TItem]: ...
    @property
    def tsts(self) -> gvec4[_TItem]: ...
    @property
    def tstt(self) -> gvec4[_TItem]: ...
    @property
    def tstp(self) -> gvec4[_TItem]: ...
    @property
    def tstq(self) -> gvec4[_TItem]: ...
    @property
    def tsps(self) -> gvec4[_TItem]: ...
    @property
    def tspt(self) -> gvec4[_TItem]: ...
    @property
    def tspp(self) -> gvec4[_TItem]: ...
    @property
    def tsqs(self) -> gvec4[_TItem]: ...
    @property
    def tsqt(self) -> gvec4[_TItem]: ...
    @property
    def tsqq(self) -> gvec4[_TItem]: ...
    @property
    def ttss(self) -> gvec4[_TItem]: ...
    @property
    def ttst(self) -> gvec4[_TItem]: ...
    @property
    def ttsp(self) -> gvec4[_TItem]: ...
    @property
    def ttsq(self) -> gvec4[_TItem]: ...
    @property
    def ttts(self) -> gvec4[_TItem]: ...
    @property
    def tttt(self) -> gvec4[_TItem]: ...
    @property
    def tttp(self) -> gvec4[_TItem]: ...
    @property
    def tttq(self) -> gvec4[_TItem]: ...
    @property
    def ttps(self) -> gvec4[_TItem]: ...
    @property
    def ttpt(self) -> gvec4[_TItem]: ...
    @property
    def ttpp(self) -> gvec4[_TItem]: ...
    @property
    def ttpq(self) -> gvec4[_TItem]: ...
    @property
    def ttqs(self) -> gvec4[_TItem]: ...
    @property
    def ttqt(self) -> gvec4[_TItem]: ...
    @property
    def ttqp(self) -> gvec4[_TItem]: ...
    @property
    def ttqq(self) -> gvec4[_TItem]: ...
    @property
    def tpss(self) -> gvec4[_TItem]: ...
    @property
    def tpst(self) -> gvec4[_TItem]: ...
    @property
    def tpsp(self) -> gvec4[_TItem]: ...
    @property
    def tpts(self) -> gvec4[_TItem]: ...
    @property
    def tptt(self) -> gvec4[_TItem]: ...
    @property
    def tptp(self) -> gvec4[_TItem]: ...
    @property
    def tptq(self) -> gvec4[_TItem]: ...
    @property
    def tpps(self) -> gvec4[_TItem]: ...
    @property
    def tppt(self) -> gvec4[_TItem]: ...
    @property
    def tppp(self) -> gvec4[_TItem]: ...
    @property
    def tppq(self) -> gvec4[_TItem]: ...
    @property
    def tpqt(self) -> gvec4[_TItem]: ...
    @property
    def tpqp(self) -> gvec4[_TItem]: ...
    @property
    def tpqq(self) -> gvec4[_TItem]: ...
    @property
    def tqss(self) -> gvec4[_TItem]: ...
    @property
    def tqst(self) -> gvec4[_TItem]: ...
    @property
    def tqsq(self) -> gvec4[_TItem]: ...
    @property
    def tqts(self) -> gvec4[_TItem]: ...
    @property
    def tqtt(self) -> gvec4[_TItem]: ...
    @property
    def tqtp(self) -> gvec4[_TItem]: ...
    @property
    def tqtq(self) -> gvec4[_TItem]: ...
    @property
    def tqpt(self) -> gvec4[_TItem]: ...
    @property
    def tqpp(self) -> gvec4[_TItem]: ...
    @property
    def tqpq(self) -> gvec4[_TItem]: ...
    @property
    def tqqs(self) -> gvec4[_TItem]: ...
    @property
    def tqqt(self) -> gvec4[_TItem]: ...
    @property
    def tqqp(self) -> gvec4[_TItem]: ...
    @property
    def tqqq(self) -> gvec4[_TItem]: ...
    @property
    def psss(self) -> gvec4[_TItem]: ...
    @property
    def psst(self) -> gvec4[_TItem]: ...
    @property
    def pssp(self) -> gvec4[_TItem]: ...
    @property
    def pssq(self) -> gvec4[_TItem]: ...
    @property
    def psts(self) -> gvec4[_TItem]: ...
    @property
    def pstt(self) -> gvec4[_TItem]: ...
    @property
    def pstp(self) -> gvec4[_TItem]: ...
    @property
    def psps(self) -> gvec4[_TItem]: ...
    @property
    def pspt(self) -> gvec4[_TItem]: ...
    @property
    def pspp(self) -> gvec4[_TItem]: ...
    @property
    def pspq(self) -> gvec4[_TItem]: ...
    @property
    def psqs(self) -> gvec4[_TItem]: ...
    @property
    def psqp(self) -> gvec4[_TItem]: ...
    @property
    def psqq(self) -> gvec4[_TItem]: ...
    @property
    def ptss(self) -> gvec4[_TItem]: ...
    @property
    def ptst(self) -> gvec4[_TItem]: ...
    @property
    def ptsp(self) -> gvec4[_TItem]: ...
    @property
    def ptts(self) -> gvec4[_TItem]: ...
    @property
    def pttt(self) -> gvec4[_TItem]: ...
    @property
    def pttp(self) -> gvec4[_TItem]: ...
    @property
    def pttq(self) -> gvec4[_TItem]: ...
    @property
    def ptps(self) -> gvec4[_TItem]: ...
    @property
    def ptpt(self) -> gvec4[_TItem]: ...
    @property
    def ptpp(self) -> gvec4[_TItem]: ...
    @property
    def ptpq(self) -> gvec4[_TItem]: ...
    @property
    def ptqt(self) -> gvec4[_TItem]: ...
    @property
    def ptqp(self) -> gvec4[_TItem]: ...
    @property
    def ptqq(self) -> gvec4[_TItem]: ...
    @property
    def ppss(self) -> gvec4[_TItem]: ...
    @property
    def ppst(self) -> gvec4[_TItem]: ...
    @property
    def ppsp(self) -> gvec4[_TItem]: ...
    @property
    def ppsq(self) -> gvec4[_TItem]: ...
    @property
    def ppts(self) -> gvec4[_TItem]: ...
    @property
    def pptt(self) -> gvec4[_TItem]: ...
    @property
    def pptp(self) -> gvec4[_TItem]: ...
    @property
    def pptq(self) -> gvec4[_TItem]: ...
    @property
    def ppps(self) -> gvec4[_TItem]: ...
    @property
    def pppt(self) -> gvec4[_TItem]: ...
    @property
    def pppp(self) -> gvec4[_TItem]: ...
    @property
    def pppq(self) -> gvec4[_TItem]: ...
    @property
    def ppqs(self) -> gvec4[_TItem]: ...
    @property
    def ppqt(self) -> gvec4[_TItem]: ...
    @property
    def ppqp(self) -> gvec4[_TItem]: ...
    @property
    def ppqq(self) -> gvec4[_TItem]: ...
    @property
    def pqss(self) -> gvec4[_TItem]: ...
    @property
    def pqsp(self) -> gvec4[_TItem]: ...
    @property
    def pqsq(self) -> gvec4[_TItem]: ...
    @property
    def pqtt(self) -> gvec4[_TItem]: ...
    @property
    def pqtp(self) -> gvec4[_TItem]: ...
    @property
    def pqtq(self) -> gvec4[_TItem]: ...
    @property
    def pqps(self) -> gvec4[_TItem]: ...
    @property
    def pqpt(self) -> gvec4[_TItem]: ...
    @property
    def pqpp(self) -> gvec4[_TItem]: ...
    @property
    def pqpq(self) -> gvec4[_TItem]: ...
    @property
    def pqqs(self) -> gvec4[_TItem]: ...
    @property
    def pqqt(self) -> gvec4[_TItem]: ...
    @property
    def pqqp(self) -> gvec4[_TItem]: ...
    @property
    def pqqq(self) -> gvec4[_TItem]: ...
    @property
    def qsss(self) -> gvec4[_TItem]: ...
    @property
    def qsst(self) -> gvec4[_TItem]: ...
    @property
    def qssp(self) -> gvec4[_TItem]: ...
    @property
    def qssq(self) -> gvec4[_TItem]: ...
    @property
    def qsts(self) -> gvec4[_TItem]: ...
    @property
    def qstt(self) -> gvec4[_TItem]: ...
    @property
    def qstq(self) -> gvec4[_TItem]: ...
    @property
    def qsps(self) -> gvec4[_TItem]: ...
    @property
    def qspp(self) -> gvec4[_TItem]: ...
    @property
    def qspq(self) -> gvec4[_TItem]: ...
    @property
    def qsqs(self) -> gvec4[_TItem]: ...
    @property
    def qsqt(self) -> gvec4[_TItem]: ...
    @property
    def qsqp(self) -> gvec4[_TItem]: ...
    @property
    def qsqq(self) -> gvec4[_TItem]: ...
    @property
    def qtss(self) -> gvec4[_TItem]: ...
    @property
    def qtst(self) -> gvec4[_TItem]: ...
    @property
    def qtsq(self) -> gvec4[_TItem]: ...
    @property
    def qtts(self) -> gvec4[_TItem]: ...
    @property
    def qttt(self) -> gvec4[_TItem]: ...
    @property
    def qttp(self) -> gvec4[_TItem]: ...
    @property
    def qttq(self) -> gvec4[_TItem]: ...
    @property
    def qtpt(self) -> gvec4[_TItem]: ...
    @property
    def qtpp(self) -> gvec4[_TItem]: ...
    @property
    def qtpq(self) -> gvec4[_TItem]: ...
    @property
    def qtqs(self) -> gvec4[_TItem]: ...
    @property
    def qtqt(self) -> gvec4[_TItem]: ...
    @property
    def qtqp(self) -> gvec4[_TItem]: ...
    @property
    def qtqq(self) -> gvec4[_TItem]: ...
    @property
    def qpss(self) -> gvec4[_TItem]: ...
    @property
    def qpsp(self) -> gvec4[_TItem]: ...
    @property
    def qpsq(self) -> gvec4[_TItem]: ...
    @property
    def qptt(self) -> gvec4[_TItem]: ...
    @property
    def qptp(self) -> gvec4[_TItem]: ...
    @property
    def qptq(self) -> gvec4[_TItem]: ...
    @property
    def qpps(self) -> gvec4[_TItem]: ...
    @property
    def qppt(self) -> gvec4[_TItem]: ...
    @property
    def qppp(self) -> gvec4[_TItem]: ...
    @property
    def qppq(self) -> gvec4[_TItem]: ...
    @property
    def qpqs(self) -> gvec4[_TItem]: ...
    @property
    def qpqt(self) -> gvec4[_TItem]: ...
    @property
    def qpqp(self) -> gvec4[_TItem]: ...
    @property
    def qpqq(self) -> gvec4[_TItem]: ...
    @property
    def qqss(self) -> gvec4[_TItem]: ...
    @property
    def qqst(self) -> gvec4[_TItem]: ...
    @property
    def qqsp(self) -> gvec4[_TItem]: ...
    @property
    def qqsq(self) -> gvec4[_TItem]: ...
    @property
    def qqts(self) -> gvec4[_TItem]: ...
    @property
    def qqtt(self) -> gvec4[_TItem]: ...
    @property
    def qqtp(self) -> gvec4[_TItem]: ...
    @property
    def qqtq(self) -> gvec4[_TItem]: ...
    @property
    def qqps(self) -> gvec4[_TItem]: ...
    @property
    def qqpt(self) -> gvec4[_TItem]: ...
    @property
    def qqpp(self) -> gvec4[_TItem]: ...
    @property
    def qqpq(self) -> gvec4[_TItem]: ...
    @property
    def qqqs(self) -> gvec4[_TItem]: ...
    @property
    def qqqt(self) -> gvec4[_TItem]: ...
    @property
    def qqqp(self) -> gvec4[_TItem]: ...
    @property
    def qqqq(self) -> gvec4[_TItem]: ...


@dataclass
class gvec2(_2d_prop[_TItem], _vec_seq[_TItem], _vec_op[_TItem], tp.Generic[_TItem]):
    @overload
    def __init__(self, p1: _UItem, p2: _UItem): ...
    @overload
    def __init__(self, p1: gvec2, p2: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: _Never = _NV): ...
    def __init__(self, p1: tp.Any, p2: tp.Any = None): ...


@dataclass
class gvec3(_3d_prop[_TItem], _vec_seq[_TItem], _vec_op[_TItem], tp.Generic[_TItem]):
    @overload
    def __init__(self, p1: _UItem, p2: _UItem, p3: _UItem): ...
    @overload
    def __init__(self, p1: gvec2, p2: _UItem, p3: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: gvec2, p3: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: _Never = _NV, p3: _Never = _NV): ...
    @overload
    def __init__(self, p1: gvec3, p2: _Never = _NV, p3: _Never = _NV): ...
    def __init__(self, p1: tp.Any, p2: tp.Any = None, p3: tp.Any = None): ...


@dataclass
class gvec4(_4d_prop[_TItem], _vec_seq[_TItem], _vec_op[_TItem], tp.Generic[_TItem]):
    @overload
    def __init__(self, p1: _UItem, p2: _UItem, p3: _UItem, p4: _UItem): ...
    @overload
    def __init__(self, p1: gvec3, p2: _UItem, p3: _Never = _NV, p4: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: gvec3, p3: _Never = _NV, p4: _Never = _NV): ...
    @overload
    def __init__(self, p1: gvec2, p2: _UItem, p3: _UItem, p4: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: gvec2, p3: _UItem, p4: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: _UItem, p3: gvec2, p4: _Never = _NV): ...
    @overload
    def __init__(self, p1: _UItem, p2: _Never = _NV, p3: _Never = _NV, p4: _Never = _NV): ...
    @overload
    def __init__(self, p1: gvec4, p2: _Never = _NV, p3: _Never = _NV, p4: _Never = _NV): ...
    def __init__(self, p1: tp.Any, p2: tp.Any = None, p3: tp.Any = None, p4: tp.Any = None): ...


vec4 = gvec4[float]
ivec4 = gvec4[int]
uvec4 = gvec4[uint]
bvec4 = gvec4[bool]
dvec4 = gvec4[double]
vec3 = gvec3[float]
ivec3 = gvec3[int]
uvec3 = gvec3[uint]
bvec3 = gvec3[bool]
dvec3 = gvec3[double]
vec2 = gvec2[float]
ivec2 = gvec2[int]
uvec2 = gvec2[uint]
bvec2 = gvec2[bool]
dvec2 = gvec2[double]
_TGenBType = tp.TypeVar('_TGenBType', bool, 'bvec2', 'bvec3', 'bvec4')
_TGenUType = tp.TypeVar('_TGenUType', uint, 'uvec2', 'uvec3', 'uvec4')
_TGenDType = tp.TypeVar('_TGenDType', double, 'dvec2', 'dvec3', 'dvec4')
_TGenIType = tp.TypeVar('_TGenIType', int, 'ivec2', 'ivec3', 'ivec4')
_TGenType = tp.TypeVar('_TGenType', float, 'vec2', 'vec3', 'vec4')
