name: Check CLA sign status

on:
  pull_request:
    types: [opened]

jobs:
  check:
    runs-on: ubuntu-20.04
    env:
      USER_NAME: ${{ github.event.pull_request.user.login }}
      IS_SIGNED: false
      CLA_REPO: "akashi-org/akashi-dev"
    if: github.event.pull_request.user.login != 'crux14'
    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ env.CLA_REPO }}
        path: cla_repo

    - name: validate sign
      run: |
        cd cla_repo
        CHECKSUM=$(md5sum cla.md | awk '{ print $1 }')
        test -f "contributors/${CHECKSUM}/${USER_NAME}.md" && (echo "IS_SIGNED=true" >> $GITHUB_ENV) || :

    - name: notify_if_not_signed
      if: env.IS_SIGNED == 'false'
      env:
        URL: ${{ github.event.pull_request.comments_url }}
      run: |
        echo "::error::We require contributors to sign our Contributor License Agreement, but you don't seem to have signed yet. In order for us to review and merge your code, please sign at https://github.com/${CLA_REPO}. For details on how to sign the Contributor License Agreement, please see https://github.com/${CLA_REPO}/blob/master/sign-cla.md. [NOTICE]: For now, we basically **only** accept pull requests from persons **who are not contributing on behalf of others.** So, if you are creating this pull request under your company's direction and control, we cannot accept your pull request."
        exit 1

